define det=TST

CREATE TABLE "REQUESTS" (

    "REQ_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "REQ_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "REQ_LOCATION_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "REQ_STATUS" VARCHAR2(20 BYTE) DEFAULT 'OPEN' NOT NULL ENABLE, 
    "REQ_COMMENT" VARCHAR2(1024 BYTE), 
    "REQ_DATE" DATE NOT NULL ENABLE, 
    "REQ_PERSON" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
    "RECORD_INSERTION_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
    "RECORD_INSERTION_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "RECORD_LASTUPDATE_TIME" TIMESTAMP (6), 
    "RECORD_LASTUPDATE_USER" VARCHAR2(50 BYTE), 

    CONSTRAINT "REQUESTS_PK" PRIMARY KEY ("REQ_ID"),
    CONSTRAINT "REQUESTS_CHK1" CHECK (REQ_STATUS in ('OPEN','CLOSED','CANCELED')) ENABLE,
    CONSTRAINT "REQUESTS_UK1" UNIQUE ("REQ_LOCATION_ID", "REQ_NAME"), 
    CONSTRAINT "REQUESTS_FK1" FOREIGN KEY ("REQ_LOCATION_ID") REFERENCES "CMS_&det._CORE_MANAGEMNT"."LOCATIONS" ("LOCATION_ID") ENABLE

);

CREATE TABLE "REQUEST_ITEMS" (

    "RQI_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "RQI_REQ_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "RQI_KIND_OF_PART_ID" NUMBER NOT NULL ENABLE, 
    "RQI_QUANTITY" NUMBER NOT NULL ENABLE,
    "RQI_COMMENT" VARCHAR2(1024 BYTE), 
    "RECORD_INSERTION_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
    "RECORD_INSERTION_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "RECORD_LASTUPDATE_TIME" TIMESTAMP (6), 
    "RECORD_LASTUPDATE_USER" VARCHAR2(50 BYTE),

    CONSTRAINT "REQUEST_ITEMS_PK" PRIMARY KEY ("RQI_ID"), 
    CONSTRAINT "REQUEST_ITEMS_CHK1" CHECK (RQI_QUANTITY > 0) ENABLE,
    CONSTRAINT "REQUEST_ITEMS_UK1" UNIQUE ("RQI_REQ_ID", "RQI_KIND_OF_PART_ID"),
    CONSTRAINT "REQUEST_ITEMS_FK1" FOREIGN KEY ("RQI_REQ_ID") REFERENCES "REQUESTS" ("REQ_ID") ENABLE, 
    CONSTRAINT "REQUEST_ITEMS_FK2" FOREIGN KEY ("RQI_KIND_OF_PART_ID") REFERENCES "KINDS_OF_PARTS" ("KIND_OF_PART_ID") ENABLE

 );

CREATE TABLE "SHIPMENTS" (

    "SHP_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "SHP_COMPANY_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
    "SHP_TRACKING_NUMBER" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
    "SHP_FROM_LOCATION_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "SHP_TO_LOCATION_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "SHP_STATUS" VARCHAR2(20 BYTE) DEFAULT 'PACKAGING' NOT NULL ENABLE, 
    "SHP_COMMENT" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
    "SHP_DATE" DATE NOT NULL ENABLE, 
    "SHP_PERSON" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
    "RECORD_INSERTION_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
    "RECORD_INSERTION_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "RECORD_LASTUPADTE_TIME" TIMESTAMP (6), 
    "RECORD_LASTUPADTE_USER" VARCHAR2(50 BYTE), 

    CONSTRAINT "SHIPMENTS_PK" PRIMARY KEY ("SHP_ID"), 
    CONSTRAINT "SHIPMENTS_CHK1" CHECK (SHP_STATUS in ('PACKAGING', 'SHIPPED','RECEIVED','CANCELED')) ENABLE, 
    CONSTRAINT "SHIPMENTS_UK1" UNIQUE ("SHP_TRACKING_NUMBER"), 
    CONSTRAINT "SHIPMENTS_FK1" FOREIGN KEY ("SHP_FROM_LOCATION_ID") REFERENCES "CMS_&det._CORE_MANAGEMNT"."LOCATIONS" ("LOCATION_ID") ENABLE, 
    CONSTRAINT "SHIPMENTS_FK2" FOREIGN KEY ("SHP_TO_LOCATION_ID") REFERENCES "CMS_&det._CORE_MANAGEMNT"."LOCATIONS" ("LOCATION_ID") ENABLE

);

CREATE TABLE "SHIPMENT_ITEMS" (

    "SHI_ID" NUMBER(32,0) NOT NULL ENABLE, 
    "SHI_SHP_ID" NUMBER NOT NULL ENABLE,
    "SHI_PART_ID" NUMBER NOT NULL ENABLE, 
    "SHI_RQI_ID" NUMBER(32,0),
    "SHI_COMMENT" VARCHAR2(1024 BYTE), 
    "RECORD_INSERTION_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
    "RECORD_INSERTION_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "RECORD_LASTUPDATE_TIME" TIMESTAMP (6), 
    "RECORD_LASTUPDATE_USER" VARCHAR2(50 BYTE), 

    CONSTRAINT "SHIPMENT_ITEMS_PK" PRIMARY KEY ("SHI_ID"),
    CONSTRAINT "SHIPMENT_ITEMS_UK1" UNIQUE ("SHI_SHP_ID", "SHI_PART_ID"),
    CONSTRAINT "SHIPMENT_ITEMS_FK1" FOREIGN KEY ("SHI_PART_ID") REFERENCES "PARTS" ("PART_ID") ENABLE, 
    CONSTRAINT "SHIPMENT_ITEMS_FK2" FOREIGN KEY ("SHI_SHP_ID")  REFERENCES "SHIPMENTS" ("SHP_ID") ENABLE, 
    CONSTRAINT "SHIPMENT_ITEMS_FK3" FOREIGN KEY ("SHI_RQI_ID")  REFERENCES "REQUEST_ITEMS" ("RQI_ID") ENABLE

);