
PROMPT Creating Index 'PRTHST_PART_FK_I'
CREATE INDEX PRTHST_PART_FK_I ON PARTS_HST
 (PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'KNDPRT_LOG_FK_I'
CREATE INDEX KNDPRT_LOG_FK_I ON KINDS_OF_PARTS
 (LPNAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'KNDPRT_MNFCTR_FK_I'
CREATE INDEX KNDPRT_MNFCTR_FK_I ON KINDS_OF_PARTS
 (MANUFACTURER_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'KNDPRT_SUBDET_FK_I'
CREATE INDEX KNDPRT_SUBDET_FK_I ON KINDS_OF_PARTS
 (SUBDETECTOR_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PRTRHST_PRTTREE_FK_I'
CREATE INDEX PRTRHST_PRTTREE_FK_I ON PHYSICAL_PARTS_TREE_HST
 (PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_HCD_END_SIDE_FK_I'
CREATE INDEX SGNCON_HCD_END_SIDE_FK_I ON SIGNAL_CONNECTIONS
 (CONNECTOR_END_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_PART_FK_I'
CREATE INDEX SGNCON_PART_FK_I ON SIGNAL_CONNECTIONS
 (PART_BEGIN_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_PART_END_SIDE_FK_I'
CREATE INDEX SGNCON_PART_END_SIDE_FK_I ON SIGNAL_CONNECTIONS
 (PART_END_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_SGCNTP_FK_I'
CREATE INDEX SGNCON_SGCNTP_FK_I ON SIGNAL_CONNECTIONS
 (SIGNAL_CONNECTION_TYPE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_HCD_FK_I'
CREATE INDEX SGNCON_HCD_FK_I ON SIGNAL_CONNECTIONS
 (CONNECTOR_BEGIN_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGNCON_PART_CABLE_FK_I'
CREATE INDEX SGNCON_PART_CABLE_FK_I ON SIGNAL_CONNECTIONS
 (CABLE_PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'KOPHST_KNDPRT_FK_I'
CREATE INDEX KOPHST_KNDPRT_FK_I ON KINDS_OF_PARTS_HST
 (KIND_OF_PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTAHST_PTAREL_FK_I'
CREATE INDEX PTAHST_PTAREL_FK_I ON PART_TO_ATTR_RLTNSHPS_HST
 (RELATIONSHIP_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'HCD_PART_FK_I'
CREATE INDEX HCD_PART_FK_I ON CONNECTORS
 (PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTPTRL_KNDPRT_FK_I'
CREATE INDEX PTPTRL_KNDPRT_FK_I ON PART_TO_PART_RLTNSHPS
 (KIND_OF_PART_ID_CHILD)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTPTRL_KNDPRT_PARENT_FK_I'
CREATE INDEX PTPTRL_KNDPRT_PARENT_FK_I ON PART_TO_PART_RLTNSHPS
 (KIND_OF_PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'MNFR_HST_MNFCTR_FK_I'
CREATE INDEX MNFR_HST_MNFCTR_FK_I ON MANUFACTURERS_HST
 (MANUFACTURER_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PATLST_PTAREL_FK_I'
CREATE INDEX PATLST_PTAREL_FK_I ON PART_ATTR_LISTS
 (RELATIONSHIP_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PATLST_PART_FK_I'
CREATE INDEX PATLST_PART_FK_I ON PART_ATTR_LISTS
 (PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PATLST_ATRBSE_FK_I'
CREATE INDEX PATLST_ATRBSE_FK_I ON PART_ATTR_LISTS
 (ATTRIBUTE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGCNTP_KNDPRT_FK_I'
CREATE INDEX SGCNTP_KNDPRT_FK_I ON SIGNAL_CONNECTION_TYPES
 (KIND_OF_PART_BEGIN_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGCNTP_KNDPRT_END_SIDE_FK_I'
CREATE INDEX SGCNTP_KNDPRT_END_SIDE_FK_I ON SIGNAL_CONNECTION_TYPES
 (KIND_OF_PART_END_SIDE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTAREL_KNDPRT_FK_I'
CREATE INDEX PTAREL_KNDPRT_FK_I ON PART_TO_ATTR_RLTNSHPS
 (KIND_OF_PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTAREL_ATRCTG_FK_I'
CREATE INDEX PTAREL_ATRCTG_FK_I ON PART_TO_ATTR_RLTNSHPS
 (ATTR_CATALOG_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PART_MNFCTR_FK_I'
CREATE INDEX PART_MNFCTR_FK_I ON PARTS
 (MANUFACTURER_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PART_KNDPRT_FK_I'
CREATE INDEX PART_KNDPRT_FK_I ON PARTS
 (KIND_OF_PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PART_LOCATN_FK_I'
CREATE INDEX PART_LOCATN_FK_I ON PARTS
 (LOCATION_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SGCNTH_SGCNTP_FK_I'
CREATE INDEX SGCNTH_SGCNTP_FK_I ON SIGNAL_CONNECTION_TYPES_HST
 (SIGNAL_CONNECTION_TYPE_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'SBDTHT_SUBDET_FK_I'
CREATE INDEX SBDTHT_SUBDET_FK_I ON SUBDETECTORS_HST
 (SUBDETECTOR_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PRTTREE_PTPTRL_FK_I'
CREATE INDEX PRTTREE_PTPTRL_FK_I ON PHYSICAL_PARTS_TREE
 (RELATIONSHIP_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PRTTREE_PRTTREE_FK_I'
CREATE INDEX PRTTREE_PRTTREE_FK_I ON PHYSICAL_PARTS_TREE
 (PART_PARENT_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PRTTREE_PART_FK_I'
CREATE INDEX PRTTREE_PART_FK_I ON PHYSICAL_PARTS_TREE
 (PART_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNRHST_HCD_FK_I'
CREATE INDEX CNRHST_HCD_FK_I ON CONNECTORS_HST
 (CONNECTOR_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PTPHST_PTPTRL_FK_I'
CREATE INDEX PTPHST_PTPTRL_FK_I ON PART_TO_PART_RLTNSHPS_HST
 (RELATIONSHIP_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX KINDOFPART_TNAME_I ON KINDS_OF_PARTS
 (EXTENSION_TABLE_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX KINDOFPART_NAME_I ON KINDS_OF_PARTS
 (DISPLAY_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX SUBDET_NAME_I ON SUBDETECTORS
 (SUBDETECTOR_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX PRTTOPRTREL_NAME_I ON PART_TO_PART_RLTNSHPS
 (DISPLAY_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX PRTTOATRREL_NAME_I ON PART_TO_ATTR_RLTNSHPS
 (DISPLAY_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX PARTS_BARCODE_I ON PARTS
 (BARCODE)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX PARTS_SERNUM_I ON PARTS
 (SERIAL_NUMBER)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX PARTS_NAMELBL_I ON PARTS
 (NAME_LABEL)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX MANUFACTURERS_NAME_I ON MANUFACTURERS
 (MANUFACTURER_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/