
PROMPT Creating Sequence 'ANY_SUBDETCTOR_ID_SEQ'
CREATE SEQUENCE ANY_SUBDETCTOR_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'PHSCLPRTSTREE_ID_SEQ'
CREATE SEQUENCE PHSCLPRTSTREE_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_PHYSCLPART_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_PHYSCLPART_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_PHYSCLPART_ID_SEQ'
CREATE SEQUENCE ANY_PHYSCLPART_ID_SEQ
 INCREMENT BY 20
 START WITH 1020
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_MNFCTR_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_MNFCTR_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_MNFCTR_ID_SEQ'
CREATE SEQUENCE ANY_MNFCTR_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_SIGCONTYPE_ID_SEQ'
CREATE SEQUENCE ANY_SIGCONTYPE_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_CONNECTOR_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_CONNECTOR_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_SIGCONTYPE_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_SIGCONTYPE_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_CONSTR_PART_ID_SEQ'
CREATE SEQUENCE ANY_CONSTR_PART_ID_SEQ
 INCREMENT BY 20
 START WITH 1001
 NOMAXVALUE
 MINVALUE 1001
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_SIGNAL_CONNECTION_ID_SEQ'
CREATE SEQUENCE ANY_SIGNAL_CONNECTION_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'PHSCLPRTSTREE_HISTORY_ID_SEQ'
CREATE SEQUENCE PHSCLPRTSTREE_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_SUBDETCTOR_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_SUBDETCTOR_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_CONNECTOR_ID_SEQ'
CREATE SEQUENCE ANY_CONNECTOR_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

