
PROMPT Granting Object Privileges
GRANT SELECT ON ANY_CONSTR_PART_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_CONSTR_PART_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT
/

GRANT SELECT ON ANY_CONSTR_PART_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON PHSCLPRTSTREE_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON PHSCLPRTSTREE_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PHSCLPRTSTREE_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT
/

GRANT SELECT ON PHSCLPRTSTREE_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_WRITER
/

GRANT SELECT ON PHSCLPRTSTREE_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_ADMIN
/


GRANT SELECT ON PHSCLPRTSTREE_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT
/

GRANT SELECT ON PHSCLPRTSTREE_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON PHSCLPRTSTREE_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_WRITER
/

GRANT SELECT ON PHSCLPRTSTREE_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PHSCLPRTSTREE_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_SUBDETCTOR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_SUBDETCTOR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_SUBDETCTOR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_SUBDETCTOR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_SIGNAL_CONNECTION_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_SIGNAL_CONNECTION_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT SELECT ON ANY_SIGCONTYPE_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_SIGCONTYPE_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_SIGCONTYPE_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_SIGCONTYPE_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_PHYSCLPART_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_PHYSCLPART_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT
/

GRANT SELECT ON ANY_PHYSCLPART_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_PHYSCLPART_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_PHYSCLPART_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_PHYSCLPART_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_PHYSCLPART_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_PHYSCLPART_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_ADMIN
/

GRANT SELECT ON ANY_PHYSCLPART_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_PHYSCLPART_HISTORY_ID_SEQ TO CMS_&det._&subdet._CONSTRUCT
/


GRANT SELECT ON ANY_MNFCTR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_MNFCTR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_MNFCTR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_MNFCTR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_CONNECTOR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_CONNECTOR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON ANY_CONNECTOR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON ANY_CONNECTOR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT SELECT ON SUBDETECTORS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT DELETE, SELECT ON SUBDETECTORS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON SUBDETECTORS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON SUBDETECTORS TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON SUBDETECTORS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON SUBDETECTORS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT DELETE, SELECT ON SIGNAL_CONNECTION_TYPES_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON SIGNAL_CONNECTION_TYPES_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT SELECT ON SIGNAL_CONNECTION_TYPES_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT SELECT ON SIGNAL_CONNECTION_TYPES TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT INSERT, UPDATE ON SIGNAL_CONNECTION_TYPES TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON SIGNAL_CONNECTION_TYPES TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT DELETE, SELECT ON SIGNAL_CONNECTIONS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON SIGNAL_CONNECTIONS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON SIGNAL_CONNECTIONS TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT SELECT ON PART_TO_PART_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT DELETE, SELECT ON PART_TO_PART_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON PART_TO_PART_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON PART_TO_PART_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON PART_TO_PART_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON PART_TO_PART_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT DELETE, SELECT ON PART_TO_ATTR_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PART_TO_ATTR_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON PART_TO_ATTR_RLTNSHPS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON PART_TO_ATTR_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PART_TO_ATTR_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON PART_TO_ATTR_RLTNSHPS TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT DELETE, SELECT ON PART_ATTR_LISTS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON PART_ATTR_LISTS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON PART_ATTR_LISTS TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT SELECT ON PARTS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT DELETE, SELECT ON PARTS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON PARTS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT INSERT, UPDATE ON PARTS TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT REFERENCES, SELECT ON PARTS TO CMS_&det._&subdet._CONSTRUCT
/

GRANT DELETE, SELECT ON PARTS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PARTS TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT REFERENCES ON PARTS TO CMS_&det._CORE_IOV_MGMNT
/

GRANT DELETE, SELECT ON MANUFACTURERS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON MANUFACTURERS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON MANUFACTURERS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT INSERT, UPDATE ON MANUFACTURERS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON MANUFACTURERS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON MANUFACTURERS TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT DELETE, SELECT ON LOGICALPARTTYPES TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON LOGICALPARTTYPES TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON LOGICALPARTTYPES TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT DELETE, SELECT ON KINDS_OF_PARTS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON KINDS_OF_PARTS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON KINDS_OF_PARTS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT SELECT ON KINDS_OF_PARTS TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT DELETE, SELECT ON KINDS_OF_PARTS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT REFERENCES, SELECT ON KINDS_OF_PARTS TO CMS_&det._CORE_COND
/

GRANT INSERT, UPDATE ON KINDS_OF_PARTS TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT SELECT ON CONNECTORS_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON CONNECTORS_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT DELETE, SELECT ON CONNECTORS_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/


GRANT DELETE, SELECT ON CONNECTORS TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON CONNECTORS TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT SELECT ON CONNECTORS TO CMS_&det._CORE_CONSTRUCT_READER
/


GRANT DELETE, SELECT ON PHYSICAL_PARTS_TREE_HST TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT SELECT ON PHYSICAL_PARTS_TREE_HST TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT INSERT, UPDATE ON PHYSICAL_PARTS_TREE_HST TO CMS_&det._CORE_CONSTRUCT_WRITER
/


GRANT REFERENCES, SELECT ON PHYSICAL_PARTS_TREE TO CMS_&det._CORE_COND
/

GRANT SELECT ON PHYSICAL_PARTS_TREE TO CMS_&det._CORE_CONSTRUCT_READER
/

GRANT DELETE, SELECT ON PHYSICAL_PARTS_TREE TO CMS_&det._CORE_CONSTRUCT_ADMIN
/

GRANT INSERT, UPDATE ON PHYSICAL_PARTS_TREE TO CMS_&det._CORE_CONSTRUCT_WRITER
/

GRANT REFERENCES, SELECT ON PHYSICAL_PARTS_TREE TO CMS_&det._&subdet._CONSTRUCT
/

GRANT REFERENCES, SELECT ON PARTS TO CMS_&det._&subdet._CONSTRUCT
/

GRANT REFERENCES, SELECT ON KINDS_OF_PARTS TO CMS_&det._&subdet._CONSTRUCT
/
