
-- Add some attributes to TEST Board

INSERT INTO CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT)
	SELECT 'TEST Position', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position');

DECLARE
  ATTR_ID NUMBER;
BEGIN
  FOR I IN 1..10 LOOP
    
    SELECT CMS_TST_CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_TST_CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position';
      
    INSERT INTO CMS_TST_CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, I, 'F');
      
  END LOOP;
END;
/
