
-- Add some attributes to TEST Position

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT 'TEST Position', 'F', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position' and IS_RECORD_DELETED = 'F');

-- Adding DELETED attribute catalog with the same DISPLAY_NAME

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT 'TEST Position', 'F', 'T'
	FROM dual
        WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position' and IS_RECORD_DELETED = 'T');

-- Add 2 indentical catalogs
INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT 'Duplicate catalog', 'F', 'F' FROM dual
	UNION ALL
	SELECT 'Duplicate catalog', 'F', 'F' FROM dual;

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_RECORD_DELETED)
VALUES ('Foil Position', 'F');

DECLARE
  ATTR_ID NUMBER;
BEGIN
  FOR I IN 1..10 LOOP

    -- NOT deleted attributes

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position' and IS_RECORD_DELETED = 'F';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, I, 'F');

    -- Deleted attributes

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Position' and IS_RECORD_DELETED = 'T';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, I, 'F');

      
  END LOOP;
END;

/
DECLARE
  ATTR_ID NUMBER;
BEGIN
  FOR I IN 1..3 LOOP

    -- NOT deleted attributes

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID FROM DUAL;
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME)
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'Foil Position' and IS_RECORD_DELETED = 'F';

    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, concat('GEM',to_char(I)), 'F');

  END LOOP;
END;

/

-- Add some attributes to TEST Dataset status

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT)
	SELECT 'TEST Dataset status', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Dataset status');

declare
  ATTR_ID number;
  ARR SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL('VALID','INVALID','GOOD','BAD');
begin
  FOR r IN ARR.first..ARR.last
  LOOP

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'COND_ALGORITHMS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'TEST Dataset status';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.COND_ALGORITHMS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, arr(r), 'F');

  END LOOP;
end;
/

-- Add some Assembly status attributes

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT 'Construction phase', 'F', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'Construction phase' and IS_RECORD_DELETED = 'F');

declare
  ATTR_ID number;
  ARR SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL('Prepared for assembly');
begin
  FOR r IN ARR.first..ARR.last
  LOOP

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'Construction phase';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, arr(r), 'F');

  END LOOP;
end;
/

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT '2S Sensor Posn', 'F', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = '2S Sensor Posn' and IS_RECORD_DELETED = 'F');

declare
  ATTR_ID number;
  ARR SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL('TOP','BOTTOM');
begin
  FOR r IN ARR.first..ARR.last
  LOOP

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = '2S Sensor Posn';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, arr(r), 'F');

  END LOOP;
end;
/

INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT,IS_RECORD_DELETED)
	SELECT 'Status', 'F', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'Status' and IS_RECORD_DELETED = 'F');

declare
  ATTR_ID number;
  ARR SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL('Good','Bad');
begin
  FOR r IN ARR.first..ARR.last
  LOOP

    SELECT CMS_&det._CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'Status';
      
    INSERT INTO CMS_&det._CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, arr(r), 'F');

  END LOOP;
end;
/