-- Create Channels table

INSERT INTO CMS_TST_CORE_COND.CHANNEL_MAPS_BASE (CHANNEL_MAP_ID,IS_RECORD_DELETED,EXTENSION_TABLE_NAME)
VALUES (1000,'F','TEST_CHANNELS');

 -- TEST_CHANNELS
INSERT INTO CMS_TST_TEST_COND.TEST_CHANNELS (CHANNEL_MAP_ID,SUBDET,IETA,IPHI,DEPTH)
VALUES ((SELECT CHANNEL_MAP_ID FROM CMS_TST_CORE_COND.CHANNEL_MAPS_BASE WHERE EXTENSION_TABLE_NAME = 'TEST_CHANNELS'),'TEST',1,1,1);

-- Create Kind of condition

INSERT INTO CMS_TST_CORE_COND.KINDS_OF_CONDITIONS (NAME, EXTENSION_TABLE_NAME, IS_RECORD_DELETED) 
   VALUES ('IV', 'TEST_IV', 'F');
   
INSERT INTO CMS_TST_CORE_COND.KINDS_OF_CONDITIONS (NAME, EXTENSION_TABLE_NAME, IS_RECORD_DELETED) 
   VALUES ('FILES', 'TEST_FILES', 'F');

-- Condition to part relationship

insert into CMS_TST_CORE_COND.COND_TO_PART_RLTNSHPS (KIND_OF_PART_ID, KIND_OF_CONDITION_ID, IS_RECORD_DELETED, DISPLAY_NAME)
select KIND_OF_PART_ID, KIND_OF_CONDITION_ID, 'F', KOP.DISPLAY_NAME || ' to ' || KOC.NAME 
  from CMS_TST_CORE_CONSTRUCT.KINDS_OF_PARTS KOP, CMS_TST_CORE_COND.KINDS_OF_CONDITIONS KOC;
   
-- Condition to attribute relationship

INSERT INTO CMS_TST_CORE_COND.COND_TO_ATTR_RLTNSHPS (KIND_OF_CONDITION_ID, ATTR_CATALOG_ID, DISPLAY_NAME, IS_RECORD_DELETED) VALUES
 ((SELECT KIND_OF_CONDITION_ID FROM CMS_TST_CORE_COND.KINDS_OF_CONDITIONS WHERE NAME='IV'),
  (SELECT ATTR_CATALOG_ID FROM CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME='TEST Dataset status'),
  'TEST',
  'F');

INSERT INTO CMS_TST_CORE_COND.COND_TO_PART_RLTNSHPS (KIND_OF_PART_ID, KIND_OF_CONDITION_ID, IS_RECORD_DELETED, DISPLAY_NAME)
      VALUES ((SELECT KIND_OF_PART_ID FROM CMS_TST_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'TEST Tower'),
                      (SELECT KIND_OF_CONDITION_ID FROM CMS_TST_CORE_COND.KINDS_OF_CONDITIONS WHERE NAME='IV'), 'F', 'TEST'); 

INSERT INTO CMS_TST_CORE_COND.COND_RUNS(COND_RUN_ID, RUN_NUMBER, RUN_TYPE, IS_RECORD_DELETED, RUN_BEGIN_TIMESTAMP)
   VALUES('9999', '1993','Vaivaras', 'F', TO_DATE('2012-03-28 11:10:00','yyyy/mm/dd hh24:mi:ss'));


INSERT INTO CMS_TST_CORE_COND.COND_DATA_SETS (COND_RUN_ID, KIND_OF_CONDITION_ID, PART_ID, IS_RECORD_DELETED, EXTENSION_TABLE_NAME, VERSION, CONDITION_DATA_SET_ID)
 VALUES((SELECT COND_RUN_ID FROM CMS_TST_CORE_COND.COND_RUNS where RUN_TYPE='Vaivaras'),
 (SELECT KIND_OF_CONDITION_ID FROM CMS_TST_CORE_COND.KINDS_OF_CONDITIONS where NAME='FILES'),
 '1000',
 'F',
 'CONFIG_DATA',
 'CONFIG_VERSION',
 '9800'
 );