CREATE TABLE "CMS_TST_TEST_COND"."HYBRID_TEST_METADATA"(
    "RECORD_ID" NUMBER NOT NULL ENABLE,
    "CONDITION_DATA_SET_ID" NUMBER NOT NULL ENABLE,
    "START_TIME" DATE,
    "END_TIME" DATE,
    "HOSTNAME" VARCHAR2(4000 BYTE),
    "USERNAME" VARCHAR2(4000 BYTE),
    "SOFTWARE" VARCHAR2(4000 BYTE),
    "PERSON_NAME" VARCHAR2(4000 BYTE),
    "PATH" VARCHAR2(4000 BYTE),
    "QUALIFICATION" VARCHAR2(4000 BYTE),
    "COMMENT_DESCRIPTION" VARCHAR2(20 BYTE),
    CONSTRAINT "HYBRID_TESTS_METADATA_PK" PRIMARY KEY ("RECORD_ID"),
    CONSTRAINT "HYBRID_TESTS_METADATA_FK1" FOREIGN KEY ("CONDITION_DATA_SET_ID") REFERENCES "CMS_TST_CORE_COND"."COND_DATA_SETS" ("CONDITION_DATA_SET_ID") ENABLE
);

GRANT SELECT ON HYBRID_TEST_METADATA TO PUBLIC;
GRANT INSERT, UPDATE ON HYBRID_TEST_METADATA TO CMS_TST_TEST_CONDITION_WRITER;

CREATE TABLE "CMS_TST_TEST_COND"."HYBRID_TEST_RESULTS"(
    "RECORD_ID" NUMBER NOT NULL ENABLE,
    "CONDITION_DATA_SET_ID" NUMBER NOT NULL ENABLE,
    "CURRENT_BEFORE" FLOAT(126),
    "CURRENT_AFTER" FLOAT(126),
    "TEMP_BEFORE" FLOAT(126),
    "TEMP_AFTER" FLOAT(126),
    "NUMBER_OF_OPEN_CHANNELS" NUMBER(32,0),
    "NUMBER_OF_SHORTED_CHANNELS" NUMBER(32,0),
    "TEST_RESULT" VARCHAR2(4000 BYTE),
    "ROOT_FILE" BLOB,
    "OPEN_CHANNELS" VARCHAR2(4000 BYTE),
    "SHORTED_CHANNELS" VARCHAR2(4000 BYTE),
     CONSTRAINT "HYBRID_TEST_RESULTS_PK" PRIMARY KEY ("RECORD_ID"),
     CONSTRAINT "HYBRID_TEST_RESULTS_FK1" FOREIGN KEY ("CONDITION_DATA_SET_ID") REFERENCES "CMS_TST_CORE_COND"."COND_DATA_SETS" ("CONDITION_DATA_SET_ID") ENABLE
);

GRANT SELECT ON HYBRID_TEST_RESULTS TO PUBLIC;
GRANT INSERT, UPDATE ON HYBRID_TEST_RESULTS TO CMS_TST_TEST_CONDITION_WRITER;

CREATE TABLE "CMS_TST_TEST_COND"."CBC_TEST_RESULTS"(
    "RECORD_ID" NUMBER NOT NULL ENABLE,
    "CBC_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "CONDITION_DATA_SET_ID" NUMBER(32,0) NOT NULL ENABLE,
    "NOISE_RMS" FLOAT(126),
    "NOISE_AVG" FLOAT(126),
    "PEDESTAL_RMS" FLOAT(126),
    "PEDESTAL_AVG" FLOAT(126),
    "THRESHOLD" VARCHAR2(4000 BYTE),
    CONSTRAINT "CBC_TESTS_RESULTS_PK" PRIMARY KEY ("RECORD_ID", "CONDITION_DATA_SET_ID"),
    CONSTRAINT "CBC_TEST_RESULTS_FK1" FOREIGN KEY ("CONDITION_DATA_SET_ID") REFERENCES "CMS_TST_CORE_COND"."COND_DATA_SETS" ("CONDITION_DATA_SET_ID") ENABLE
);

GRANT SELECT ON CBC_TEST_RESULTS TO PUBLIC;
GRANT INSERT, UPDATE ON CBC_TEST_RESULTS TO CMS_TST_TEST_CONDITION_WRITER;