WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT ----------------------------------------------------------

PROMPT Cleaning db records for tests

PROMPT connecting to CMS_TST_CORE_IOV_MGMNT
connect CMS_TST_CORE_IOV_MGMNT/testing@&&1

PROMPT Deleting CMS_TST_CORE_IOV_MGMNT.COND_DATASET2IOV_MAPS table.
delete from CMS_TST_CORE_IOV_MGMNT.COND_DATASET2IOV_MAPS
/
PROMPT Deleting CMS_TST_CORE_IOV_MGMNT.COND_IOV2TAG_MAPS table.
delete from CMS_TST_CORE_IOV_MGMNT.COND_IOV2TAG_MAPS
/
PROMPT Deleting CMS_TST_CORE_IOV_MGMNT.COND_TAGS table.
delete from CMS_TST_CORE_IOV_MGMNT.COND_TAGS
/
PROMPT Deleting CMS_TST_CORE_IOV_MGMNT.COND_IOVS table.
delete from CMS_TST_CORE_IOV_MGMNT.COND_IOVS
/

PROMPT connecting to CMS_TST_CORE_COND
connect CMS_TST_CORE_COND/testing@&&1


PROMPT Deleting CMS_TST_CORE_COND.COND_ATTR_LISTS table.
delete from CMS_TST_CORE_COND.COND_ATTR_LISTS
/
PROMPT Deleting CMS_TST_CORE_COND.COND_TO_ATTR_RLTNSHPS table.
delete from CMS_TST_CORE_COND.COND_TO_ATTR_RLTNSHPS
/
PROMPT Deleting CMS_TST_CORE_COND.COND_TO_PART_RLTNSHPS table.
delete from CMS_TST_CORE_COND.COND_TO_PART_RLTNSHPS
/
PROMPT Deleting CMS_TST_CORE_COND.COND_DATA_SETS
delete from CMS_TST_CORE_COND.COND_DATA_SETS
/
PROMPT Deleting CMS_TST_CORE_COND.CHANNEL_MAPS_BASE table.
delete from CMS_TST_CORE_COND.CHANNEL_MAPS_BASE
/
PROMPT Deleting CMS_TST_CORE_COND.KINDS_OF_CONDITIONS table.
delete from CMS_TST_CORE_COND.KINDS_OF_CONDITIONS
/
PROMPT Deleting CMS_TST_CORE_COND.COND_RUNS table.
delete from CMS_TST_CORE_COND.COND_RUNS
/

PROMPT connecting to CMS_TST_CORE_CONSTRUCT
connect CMS_TST_CORE_CONSTRUCT/testing@&&1

PROMPT Deleting CMS_TST_CORE_CONSTRUCT.PHYSICAL_PARTS_TREE table.
delete from CMS_TST_CORE_CONSTRUCT.PHYSICAL_PARTS_TREE
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.PART_ATTR_LISTS table.
delete from CMS_TST_CORE_CONSTRUCT.PART_ATTR_LISTS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.PARTS table.
delete from CMS_TST_CORE_CONSTRUCT.PARTS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.PART_TO_ATTR_RLTNSHPS table.
delete from CMS_TST_CORE_CONSTRUCT.PART_TO_ATTR_RLTNSHPS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.PART_TO_PART_RLTNSHPS table.
delete from CMS_TST_CORE_CONSTRUCT.PART_TO_PART_RLTNSHPS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.KINDS_OF_PARTS table.
delete from CMS_TST_CORE_CONSTRUCT.KINDS_OF_PARTS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.SUBDETECTORS table.
delete from CMS_TST_CORE_CONSTRUCT.SUBDETECTORS
/
PROMPT Deleting CMS_TST_CORE_CONSTRUCT.MANUFACTURERS table.
delete from CMS_TST_CORE_CONSTRUCT.MANUFACTURERS
/

PROMPT connecting to CMS_TST_CORE_ATTRIBUTE
connect CMS_TST_CORE_ATTRIBUTE/testing@&&1

PROMPT Deleting CMS_TST_CORE_ATTRIBUTE.POSITION_SCHEMAS table.
delete from CMS_TST_CORE_ATTRIBUTE.POSITION_SCHEMAS
/
PROMPT Deleting CMS_TST_CORE_ATTRIBUTE.COND_ALGORITHMS table.
delete from CMS_TST_CORE_ATTRIBUTE.COND_ALGORITHMS
/
PROMPT Deleting CMS_TST_CORE_ATTRIBUTE.ATTR_BASES table.
delete from CMS_TST_CORE_ATTRIBUTE.ATTR_BASES
/
PROMPT Deleting CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS table.
delete from CMS_TST_CORE_ATTRIBUTE.ATTR_CATALOGS
/

PROMPT connecting to CMS_TST_TEST_COND
connect CMS_TST_TEST_COND/testing@&&1

PROMPT Drop CMS_TST_TEST_COND.TEST_COORDINATES table.
drop table CMS_TST_TEST_COND.TEST_COORDINATES
/

PROMPT Drop CMS_TST_TEST_COND.TEST_CHANNELS table.
drop table CMS_TST_TEST_COND.TEST_CHANNELS
/
PROMPT Drop CMS_TST_TEST_COND.TEST_FILES table.
drop table CMS_TST_TEST_COND.TEST_FILES
/
PROMPT Drop CMS_TST_TEST_COND.TEST_IV table.
drop table CMS_TST_TEST_COND.TEST_IV
/

PROMPT connecting to CMS_TST_CORE_MANAGEMNT
connect CMS_TST_CORE_MANAGEMNT/testing@&&1

PROMPT Deleting CMS_TST_CORE_MANAGEMNT.CONDITIONS_DATA_AUDITLOG table.
delete from CMS_TST_CORE_MANAGEMNT.CONDITIONS_DATA_AUDITLOG
/
PROMPT Deleting CMS_TST_CORE_MANAGEMNT.LOCATIONS table.
delete from CMS_TST_CORE_MANAGEMNT.LOCATIONS
/
PROMPT Deleting CMS_TST_CORE_MANAGEMNT.INSTITUTIONS table.
delete from CMS_TST_CORE_MANAGEMNT.INSTITUTIONS
/

@create.sql

quit