-- Add required subdetector

INSERT INTO CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS (SUBDETECTOR_NAME, IS_RECORD_DELETED) 
    SELECT 'GEM', 'F' 
    FROM dual 
    WHERE NOT EXISTS (select * 
    FROM CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS
    WHERE (SUBDETECTOR_NAME ='GEM' AND IS_RECORD_DELETED = 'F'));

-- Add some kind of parts
 
INSERT INTO CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS (SUBDETECTOR_ID, EXTENSION_TABLE_NAME, IS_RECORD_DELETED, IS_DETECTOR_PART, IS_IMAGINARY_PART, DISPLAY_NAME)
   SELECT (SELECT SUBDETECTOR_ID FROM CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS where SUBDETECTOR_NAME = 'GEM'), 'PART','F', 'F', 'F', 'GEM ROOT' 
   FROM dual 
   WHERE NOT EXISTS (select * from CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM ROOT');
 
INSERT INTO CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS (SUBDETECTOR_ID, EXTENSION_TABLE_NAME, IS_RECORD_DELETED, IS_DETECTOR_PART, IS_IMAGINARY_PART, DISPLAY_NAME)
   SELECT (SELECT SUBDETECTOR_ID FROM CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS where SUBDETECTOR_NAME = 'GEM'), 'PART','F', 'F', 'F', 'GEM Tower' 
   FROM dual 
   WHERE NOT EXISTS (select * from CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM Tower');

INSERT INTO CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS (SUBDETECTOR_ID, EXTENSION_TABLE_NAME, IS_RECORD_DELETED, IS_DETECTOR_PART, IS_IMAGINARY_PART, DISPLAY_NAME)
   SELECT (SELECT SUBDETECTOR_ID FROM CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS where SUBDETECTOR_NAME = 'GEM'), 'PART','F', 'F', 'F', 'GEM Pack' 
   FROM DUAL 
   WHERE NOT EXISTS (select * from CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM Pack');

INSERT INTO CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS (SUBDETECTOR_ID, EXTENSION_TABLE_NAME, IS_RECORD_DELETED, IS_DETECTOR_PART, IS_IMAGINARY_PART, DISPLAY_NAME)
   SELECT (SELECT SUBDETECTOR_ID FROM CMS_GEM_CORE_CONSTRUCT.SUBDETECTORS where SUBDETECTOR_NAME = 'GEM'), 'PART','F', 'F', 'F', 'GEM Board' 
   FROM dual 
   WHERE NOT EXISTS (select * from CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM Board');

-- Add ROOT part and relation to itself

INSERT INTO CMS_GEM_CORE_CONSTRUCT.PARTS (KIND_OF_PART_ID, IS_RECORD_DELETED, NAME_LABEL)
   SELECT KIND_OF_PART_ID, 'F', 'ROOT' 
   FROM CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS where DISPLAY_NAME = 'GEM ROOT';

INSERT INTO CMS_GEM_CORE_CONSTRUCT.PART_TO_PART_RLTNSHPS (KIND_OF_PART_ID, KIND_OF_PART_ID_CHILD, IS_RECORD_DELETED, PRIORITY_NUMBER, DISPLAY_NAME)
    SELECT KIND_OF_PART_ID, KIND_OF_PART_ID, 'F', 0, 'ROOT-ROOT' 
    FROM CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS where DISPLAY_NAME = 'GEM ROOT';

INSERT INTO CMS_GEM_CORE_CONSTRUCT.PHYSICAL_PARTS_TREE (PART_ID, RELATIONSHIP_ID, PART_PARENT_ID, IS_RECORD_DELETED)
    SELECT PART_ID, RELATIONSHIP_ID, PART_ID, 'F'
    FROM 
      CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS KOP 
      JOIN CMS_GEM_CORE_CONSTRUCT.PARTS P ON KOP.KIND_OF_PART_ID = P.KIND_OF_PART_ID 
      JOIN CMS_GEM_CORE_CONSTRUCT.PART_TO_PART_RLTNSHPS R ON KOP.KIND_OF_PART_ID = R.KIND_OF_PART_ID and KOP.KIND_OF_PART_ID = R.KIND_OF_PART_ID_CHILD
    WHERE KOP.DISPLAY_NAME = 'GEM ROOT' AND P.NAME_LABEL = 'ROOT';

-- Add some attributes to GEM Board

INSERT INTO CMS_GEM_CORE_ATTRIBUTE.ATTR_CATALOGS (DISPLAY_NAME, IS_UNIQUE_WITHIN_PARENT)
	SELECT 'GEM Position', 'F'
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM CMS_GEM_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'GEM Position');

INSERT INTO CMS_GEM_CORE_CONSTRUCT.PART_TO_ATTR_RLTNSHPS (ATTR_CATALOG_ID, KIND_OF_PART_ID, DISPLAY_NAME)
   SELECT (SELECT ATTR_CATALOG_ID FROM CMS_GEM_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'GEM Position'), 
          (SELECT KIND_OF_PART_ID FROM CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM Board'),
          'GEM Board Position'
   FROM dual
   WHERE NOT EXISTS (SELECT * FROM CMS_GEM_CORE_CONSTRUCT.PART_TO_ATTR_RLTNSHPS WHERE DISPLAY_NAME = 'GEM Board Position');

DECLARE
  ATTR_ID NUMBER;
BEGIN
  FOR I IN 1..10 LOOP
    
    SELECT CMS_GEM_CORE_ATTRIBUTE.PREDEF_ATTR_ID_SEQ.NEXTVAL INTO ATTR_ID  FROM DUAL;
    
    INSERT INTO CMS_GEM_CORE_ATTRIBUTE.ATTR_BASES (ATTRIBUTE_ID, ATTR_CATALOG_ID, EXTENSION_TABLE_NAME) 
      SELECT ATTR_ID, ATTR_CATALOG_ID, 'POSITION_SCHEMAS' FROM CMS_GEM_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME = 'GEM Position';
      
    INSERT INTO CMS_GEM_CORE_ATTRIBUTE.POSITION_SCHEMAS (ATTRIBUTE_ID, NAME, IS_RECORD_DELETED) VALUES (ATTR_ID, I, 'F');
      
  END LOOP;
END;
/
