-- Create Channels table

CREATE TABLE "CMS_GEM_MUON_COND"."GEM_CHANNELS" (	
  "CHANNEL_MAP_ID" NUMBER, 
	"SUBDET" VARCHAR2(20 BYTE), 
	"IETA" NUMBER, 
	"IPHI" NUMBER, 
	"DEPTH" NUMBER
   );

ALTER TABLE "CMS_GEM_MUON_COND"."GEM_CHANNELS" ADD CONSTRAINT "GEM_CHANNEL_MAP_PK" PRIMARY KEY ("CHANNEL_MAP_ID");

DECLARE
  CH_ID number;
BEGIN
  FOR IETA IN 1..10 LOOP
    FOR IPHI IN 1..10 LOOP
      FOR DEPTH IN 1..10 LOOP
      
        SELECT CMS_GEM_CORE_COND.ANY_COND_RECORD_ID_SEQ.NEXTVAL INTO CH_ID FROM dual;
    
        INSERT INTO CMS_GEM_CORE_COND.CHANNEL_MAPS_BASE (CHANNEL_MAP_ID, IS_RECORD_DELETED, EXTENSION_TABLE_NAME)
          VALUES (CH_ID, 'F', 'GEM_CHANNELS');
    
        INSERT INTO CMS_GEM_MUON_COND.GEM_CHANNELS (CHANNEL_MAP_ID, SUBDET, IETA, IPHI, DEPTH) 
        VALUES (CH_ID, 'GEM', IETA, IPHI, DEPTH);
        
      END LOOP;
    END LOOP;
  END LOOP;
END;
/

-- Create Kind of condition

CREATE TABLE "CMS_GEM_MUON_COND"."GEM_IV" (	
  "RECORD_ID" NUMBER, 
	"CONDITION_DATA_SET_ID" NUMBER, 
	"VOLTAGE" NUMBER, 
	"CURR" NUMBER, 
	"COMMENT_DESCRIPTION" VARCHAR2(128 BYTE)
   );
   
ALTER TABLE "CMS_GEM_MUON_COND"."GEM_IV" ADD CONSTRAINT "GEM_IV_PK" PRIMARY KEY ("RECORD_ID");
   
GRANT SELECT, INSERT on "CMS_GEM_MUON_COND"."GEM_IV" to "CMS_GEM_PRTTYPE_MUON_WRITER" ;

INSERT INTO CMS_GEM_CORE_COND.KINDS_OF_CONDITIONS (NAME, EXTENSION_TABLE_NAME, IS_RECORD_DELETED) 
   VALUES ('IV', 'GEM_IV', 'F');
   
-- Create Kind of condition with LOBs

CREATE TABLE "CMS_GEM_MUON_COND"."GEM_FILES" (	
  "RECORD_ID" NUMBER NOT NULL ENABLE, 
	"CONDITION_DATA_SET_ID" NUMBER NOT NULL ENABLE, 
	"GEM_TEXT_FILE" VARCHAR2(256 BYTE), 
	"GEM_MEDIA_FILE" VARCHAR2(256 BYTE), 
	"GEM_TEXT_CLOB" CLOB, 
	"GEM_MEDIA_BLOB" BLOB, 
	"GEM_COMMENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "GEM_FILES_PK" PRIMARY KEY ("RECORD_ID")
); 

GRANT SELECT, INSERT on "CMS_GEM_MUON_COND"."GEM_FILES" to "CMS_GEM_PRTTYPE_MUON_WRITER" ;

INSERT INTO CMS_GEM_CORE_COND.KINDS_OF_CONDITIONS (NAME, EXTENSION_TABLE_NAME, IS_RECORD_DELETED) 
   VALUES ('FILES', 'GEM_FILES', 'F');
   