-- Insert to CMS_GEM_CORE_COND.COND_TO_ATTR_RLTNSHP
INSERT INTO CMS_GEM_CORE_COND.COND_TO_ATTR_RLTNSHPS (KIND_OF_CONDITION_ID, ATTR_CATALOG_ID, DISPLAY_NAME, IS_RECORD_DELETED) VALUES
 ((SELECT KIND_OF_CONDITION_ID FROM CMS_GEM_CORE_COND.KINDS_OF_CONDITIONS WHERE NAME='IV'),
  (SELECT ATTR_CATALOG_ID FROM CMS_GEM_CORE_ATTRIBUTE.ATTR_CATALOGS WHERE DISPLAY_NAME='GEM Position'),
  'TEST',
  'F');

 -- Insert to CMS_GEM_CORE_COND.COND_TO_PART_RLTNSHPS
 INSERT INTO CMS_GEM_CORE_COND.COND_TO_PART_RLTNSHPS (KIND_OF_PART_ID, KIND_OF_CONDITION_ID, IS_RECORD_DELETED, DISPLAY_NAME)
 	VALUES ((SELECT KIND_OF_PART_ID FROM CMS_GEM_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE DISPLAY_NAME = 'GEM Tower'),
 			(SELECT KIND_OF_CONDITION_ID FROM CMS_GEM_CORE_COND.KINDS_OF_CONDITIONS WHERE NAME='IV'), 'F', 'TEST'); 

