
PROMPT Creating Table 'COND_TAGS'
CREATE TABLE COND_TAGS
 (COND_TAG_ID NUMBER(38,0) NOT NULL
 ,COND_TAG_PARENT_ID NUMBER(38,0)
 ,IS_RECORD_DELETED CHAR(1) DEFAULT 'F' NOT NULL
 ,TAG_NAME VARCHAR2(40) NOT NULL
 ,RECORD_INSERTION_TIME TIMESTAMP WITH TIME ZONE NOT NULL
 ,RECORD_INSERTION_USER VARCHAR2(50) NOT NULL
 ,RECORD_DEL_FLAG_TIME TIMESTAMP WITH TIME ZONE
 ,RECORD_DEL_FLAG_USER VARCHAR2(50)
 ,DETECTOR_NAME VARCHAR2(40)
 ,COMMENT_DESCRIPTION VARCHAR2(4000)
 )
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'COND_IOV2TAG_MAPS'
CREATE TABLE COND_IOV2TAG_MAPS
 (COND_TAG_ID NUMBER(38,0) NOT NULL
 ,COND_IOV_RECORD_ID NUMBER(38,0) NOT NULL
 )
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'COND_DATASET2IOV_MAPS'
CREATE TABLE COND_DATASET2IOV_MAPS
 (COND_IOV_RECORD_ID NUMBER(38,0) NOT NULL
 ,CONDITION_DATA_SET_ID NUMBER(38,0) NOT NULL
 )
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'COND_IOVS'
CREATE TABLE COND_IOVS
 (COND_IOV_RECORD_ID NUMBER(38,0) NOT NULL
 ,IS_RECORD_DELETED CHAR(1) NOT NULL
 ,INTERVAL_OF_VALIDITY_BEGIN NUMBER(38) NOT NULL
 ,RECORD_INSERTION_TIME TIMESTAMP WITH TIME ZONE NOT NULL
 ,RECORD_INSERTION_USER VARCHAR2(50) NOT NULL
 ,INTERVAL_OF_VALIDITY_END NUMBER(38)
 ,RECORD_DEL_FLAG_TIME TIMESTAMP WITH TIME ZONE
 ,RECORD_DEL_FLAG_USER VARCHAR2(50)
 )
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

