
PROMPT Creating Index 'CNDTAG_CNDTAG_FK_I'
CREATE INDEX CNDTAG_CNDTAG_FK_I ON COND_TAGS
 (COND_TAG_PARENT_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDTAG_NAME_IDX'
CREATE INDEX CNDTAG_NAME_IDX ON COND_TAGS
 (TAG_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDTAG_DET_NAME_IDX'
CREATE INDEX CNDTAG_DET_NAME_IDX ON COND_TAGS
 (DETECTOR_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDIOV2TAG_CNDIOV_FK_I'
CREATE INDEX CNDIOV2TAG_CNDIOV_FK_I ON COND_IOV2TAG_MAPS
 (COND_IOV_RECORD_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDIOV2TAG_CNDTAG_FK_I'
CREATE INDEX CNDIOV2TAG_CNDTAG_FK_I ON COND_IOV2TAG_MAPS
 (COND_TAG_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDDSIOVMP_CNDTST_FK_I'
CREATE INDEX CNDDSIOVMP_CNDTST_FK_I ON COND_DATASET2IOV_MAPS
 (CONDITION_DATA_SET_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDDSIOVMP_CNDIOV_FK_I'
CREATE INDEX CNDDSIOVMP_CNDIOV_FK_I ON COND_DATASET2IOV_MAPS
 (COND_IOV_RECORD_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDIOV_IOV_BEG_IDX'
CREATE INDEX CNDIOV_IOV_BEG_IDX ON COND_IOVS
 (INTERVAL_OF_VALIDITY_BEGIN)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDIOV_IOV_END_IDX'
CREATE INDEX CNDIOV_IOV_END_IDX ON COND_IOVS
 (INTERVAL_OF_VALIDITY_END)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

