
PROMPT Creating Sequence 'CNDIOV_ID_SEQ'
CREATE SEQUENCE CNDIOV_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
 ORDER
/

PROMPT Creating Sequence 'CNDTAG_ID_SEQ'
CREATE SEQUENCE CNDTAG_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
 ORDER
/

GRANT SELECT ON  CMS_&det._CORE_IOV_MGMNT.CNDIOV_ID_SEQ TO CMS_&det._CORE_IOV_MGMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_IOV_MGMNT.CNDIOV_ID_SEQ TO CMS_&det._CORE_IOV_MGMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_IOV_MGMNT.CNDTAG_ID_SEQ TO CMS_&det._CORE_IOV_MGMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_IOV_MGMNT.CNDTAG_ID_SEQ TO CMS_&det._CORE_IOV_MGMNT_WRITER;

