
PROMPT Creating Table 'CONFIG_KEYS'
CREATE TABLE CONFIG_KEYS
(CONFIG_KEY_ID NUMBER(38, 0) NOT NULL
,CONFIG_KEY_TYPE_ID NUMBER(38, 0) NOT NULL
,IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
,NAME VARCHAR2(80 BYTE) NOT NULL
,RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
,RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
,RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
,RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
,COMMENT_DESCRIPTION VARCHAR2(4000 BYTE)
,PROVENANCE VARCHAR2(4000 BYTE)
,CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
,CREATED_BY_USER VARCHAR2(50 BYTE)
)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'CONFIG_KEY_ALIAS_MAPS'
CREATE TABLE CONFIG_KEY_ALIAS_MAPS
(
 CONFIG_KEY_ALIAS_MAP_ID NUMBER(38, 0) NOT NULL
,CONFIG_KEY_ALIAS_ID NUMBER(38, 0) NOT NULL
,CONFIG_KEY_ID NUMBER(38, 0) NOT NULL
,IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
,IS_MOVED_TO_HISTORY CHAR(1 BYTE) DEFAULT 'F' NOT NULL
,RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
,RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
,RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
,RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
,CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
,CREATED_BY_USER VARCHAR2(50 BYTE)
)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'CONFIG_KEY_ALIASES'
CREATE TABLE CONFIG_KEY_ALIASES
 (
  CONFIG_KEY_ALIAS_ID NUMBER(38, 0) NOT NULL
 ,IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
 ,NAME VARCHAR2(80 BYTE) NOT NULL
 ,RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
 ,RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
 ,RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
 ,RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
 ,COMMENT_DESCRIPTION VARCHAR2(4000 BYTE)
 ,CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
 ,CREATED_BY_USER VARCHAR2(50 BYTE)
 )
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'CONFIG_KEY_RUN_HST'
CREATE TABLE CONFIG_KEY_RUN_HST
  (
   CONFIG_KEY_RUN_HST_ID NUMBER(38, 0) NOT NULL
  ,COND_RUN_ID NUMBER(38, 0) NOT NULL
  ,CONFIG_KEY_ID NUMBER(38, 0) NOT NULL
  ,IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
  ,NAME VARCHAR2(80 BYTE) NOT NULL
  ,RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  ,RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  ,RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
  ,RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
  ,COMMENT_DESCRIPTION VARCHAR2(4000 BYTE)
  ,CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  ,CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'CONFIG_KEY_SUBVER_MAPS_HST'
CREATE TABLE CONFIG_KEY_SUBVER_MAPS_HST
  (
    CONFIG_KEY_SUBVER_MAP_HST_ID NUMBER(38, 0) NOT NULL
  , CONDITION_DATA_SET_ID NUMBER(38, 0) NOT NULL
  , CONFIG_KEY_RUN_HST_ID NUMBER(38, 0) NOT NULL
  , CONFIG_KEY_VERSION_MAP_ID NUMBER(38, 0) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , RECORD_LASTUPDATE_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_LASTUPDATE_USER VARCHAR2(50 BYTE)
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/
--CONFIG_KEY_TYPES
PROMPT Creating Table 'CONFIG_KEY_TYPES'
CREATE TABLE CONFIG_KEY_TYPES
  (
   CONFIG_KEY_TYPE_ID NUMBER(38, 0) NOT NULL
  , IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
  , NAME VARCHAR2(80 BYTE) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
  , COMMENT_DESCRIPTION VARCHAR2(4000 BYTE)
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/


--CREATE TABLE CONFIG_VERSION_ALIASES
PROMPT Creating Table 'CONFIG_VERSION_ALIASES'
CREATE TABLE CONFIG_VERSION_ALIASES
  (
    CONFIG_VERSION_ALIAS_ID NUMBER(38, 0) NOT NULL
  , IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
  , NAME VARCHAR2(80 BYTE) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
  , COMMENT_DESCRIPTION VARCHAR2(4000 BYTE)
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Table 'CONFIG_KEY_VERSION_ALIAS_MAPS'
CREATE TABLE CONFIG_KEY_VERSION_ALIAS_MAPS
  (
   CONFIG_KEY_VERSION_ALIAS_ID NUMBER(38, 0) NOT NULL
  , CONFIG_KEY_ALIAS_ID NUMBER(38, 0) NOT NULL
  , CONFIG_VERSION_ALIAS_ID NUMBER(38, 0) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , IS_MOVED_TO_HISTORY CHAR(1 BYTE) NOT NULL
  , KIND_OF_CONDITION_ID NUMBER(38, 0)
  , RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
  , IS_RECORD_DELETED CHAR(1 BYTE)
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/


PROMPT Creating Table 'CONFIG_KEY_VERSION_MAPS'
CREATE TABLE CONFIG_KEY_VERSION_MAPS
  (
   CONFIG_KEY_VERSION_MAP_ID NUMBER(38, 0) NOT NULL
  , CONDITION_DATA_SET_ID NUMBER(38, 0) NOT NULL
  , CONFIG_KEY_ID NUMBER(38, 0) NOT NULL
  , CONFIG_TYPE_KOC_MAP_ID NUMBER(38, 0)
  , SUBVERSION_COND_DATA_SET_ID NUMBER(38, 0) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , RECORD_LASTUPDATE_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_LASTUPDATE_USER VARCHAR2(50 BYTE)
  , IS_MOVED_TO_HISTORY CHAR(1 BYTE) NOT NULL
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/


PROMPT Creating Table 'CONFIG_TYPE_KOC_PART_MAPS'
CREATE TABLE CONFIG_TYPE_KOC_PART_MAPS
  (
   CONFIG_TYPE_KOC_MAP_ID NUMBER(38, 0) NOT NULL
  , CONFIG_KEY_TYPE_ID NUMBER(38, 0) NOT NULL
  , KIND_OF_CONDITION_ID NUMBER(38, 0) NOT NULL
  , PART_ID NUMBER(38, 0) NOT NULL
  , IS_RECORD_DELETED CHAR(1 BYTE) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , KOC_ORDER VARCHAR2(240 BYTE)
  , RECORD_DEL_FLAG_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_DEL_FLAG_USER VARCHAR2(50 BYTE)
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/


PROMPT Creating Table 'CONFIG_VERSION_ALIAS_MAPS'
CREATE TABLE CONFIG_VERSION_ALIAS_MAPS
  (
   CONFIG_VERSION_ALIAS_MAP_ID NUMBER(38, 0) NOT NULL
  , SUBVERSION_COND_DATA_SET_ID NUMBER(38, 0)
  , CONDITION_DATA_SET_ID NUMBER(38, 0) NOT NULL
  , CONFIG_VERSION_ALIAS_ID NUMBER(38, 0) NOT NULL
  , RECORD_INSERTION_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL
  , RECORD_INSERTION_USER VARCHAR2(50 BYTE) NOT NULL
  , RECORD_LASTUPDATE_TIME TIMESTAMP(6) WITH TIME ZONE
  , RECORD_LASTUPDATE_USER VARCHAR2(50 BYTE)
  , IS_MOVED_TO_HISTORY CHAR(1 BYTE) NOT NULL
  , CREATE_TIMESTAMP TIMESTAMP(6) WITH TIME ZONE
  , CREATED_BY_USER VARCHAR2(50 BYTE)
  )
TABLESPACE CMS_&det._PROCERNIT_DATA
/

-