
--CONFIG_KEYS
PROMPT Creating Index 'CNFKEY_CNFKEYTYP_FK_I'
CREATE INDEX CNFKEY_CNFKEYTYP_FK_I ON CONFIG_KEYS
 (CONFIG_KEY_TYPE_ID ASC)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONFIG_KEYS_PK'
CREATE INDEX CONFIG_KEYS_PK ON CONFIG_KEYS
 (CONFIG_KEY_ID ASC)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/
--CONFIG_KEY_ALIAS_MAPS
PROMPT Creating Index 'CFGKEYALM_CNFKEYALS_FK_I'
CREATE INDEX CFGKEYALM_CNFKEYALS_FK_I ON CONFIG_KEY_ALIAS_MAPS
 (CONFIG_KEY_ALIAS_ID ASC)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CFGKEYALM_CNFKEY_FK_I'
CREATE INDEX CFGKEYALM_CNFKEY_FK_I ON CONFIG_KEY_ALIAS_MAPS
  (CONFIG_KEY_ID ASC)
  TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONFKEYDELHIST'
CREATE INDEX CONFKEYDELHIST ON CONFIG_KEY_ALIAS_MAPS
  (IS_RECORD_DELETED ASC,
   IS_MOVED_TO_HISTORY ASC)
  TABLESPACE CMS_&det._PROCERNIT_DATA
/


--CONFIG_KEY_ALIASES
PROMPT Creating Unique Index 'CONFIG_KEY_ALIASES_PK'
CREATE UNIQUE INDEX CONFIG_KEY_ALIASES_PK ON CONFIG_KEY_ALIASES
  (CONFIG_KEY_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONFKANDEL1'
CREATE INDEX CONFKANDEL1 ON CONFIG_KEY_ALIASES
  (NAME ASC,
   IS_RECORD_DELETED ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONFKEYALDEL1'
CREATE INDEX CONFKEYALDEL1 ON CONFIG_KEY_ALIASES
  (IS_RECORD_DELETED ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

--CONFIG_KEY_RUN_HST
PROMPT Creating Index 'CONKRHST_CNDRUN_FK_I'
CREATE INDEX CONKRHST_CNDRUN_FK_I ON CONFIG_KEY_RUN_HST
  (COND_RUN_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONKRHST_CNFKEY_FK_I'
CREATE INDEX CONKRHST_CNFKEY_FK_I ON CONFIG_KEY_RUN_HST
  (CONFIG_KEY_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

--CONFIG_KEY_SUBVER_MAPS_HST
PROMPT Creating Index 'CONKSVMHST_CONKRHST_FK_I'
CREATE INDEX CONKSVMHST_CONKRHST_FK_I ON CONFIG_KEY_SUBVER_MAPS_HST
  (CONFIG_KEY_RUN_HST_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONKSVMHST_CNFKEYVER_FK_I'
CREATE INDEX CONKSVMHST_CNFKEYVER_FK_I ON CONFIG_KEY_SUBVER_MAPS_HST
  (CONFIG_KEY_VERSION_MAP_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONKSVMHST_CNDTST_FK_I'
CREATE INDEX CONKSVMHST_CNDTST_FK_I ON CONFIG_KEY_SUBVER_MAPS_HST
  (CONDITION_DATA_SET_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

--CONFIG_KEY_TYPES
PROMPT Creating Index 'CONFTYPES1'
CREATE INDEX CONFTYPES1 ON CONFIG_KEY_TYPES
  (NAME ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/
--CONFIG_KEY_VERSION_ALIAS_MAPS
PROMPT Creating Index 'CONVERKEYALMP_PK'
CREATE UNIQUE INDEX CONVERKEYALMP_PK ON CONFIG_KEY_VERSION_ALIAS_MAPS
  (CONFIG_KEY_VERSION_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERALMP_CONVERVALS_FK_I'
CREATE INDEX CONVERALMP_CONVERVALS_FK_I ON CONFIG_KEY_VERSION_ALIAS_MAPS
  (CONFIG_VERSION_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERALMP_CONVERKALS_FK_I'
CREATE INDEX CONVERALMP_CONVERKALS_FK_I ON CONFIG_KEY_VERSION_ALIAS_MAPS
  (CONFIG_KEY_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

--CONFIG_VERSION_ALIASES


PROMPT Creating Index 'CONVERALS_PK'
CREATE UNIQUE INDEX CONVERALS_PK ON CONFIG_VERSION_ALIASES
  (CONFIG_VERSION_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERADEL1'
CREATE INDEX CONVERADEL1 ON CONFIG_VERSION_ALIASES
  (CONFIG_VERSION_ALIAS_ID ASC,
   IS_RECORD_DELETED ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

--CONFIG_KEY_VERSION_MAPS
PROMPT Creating Index 'CNFKEYVER_CNDTST_FK_I'
CREATE INDEX CNFKEYVER_CNDTST_FK_I ON CONFIG_KEY_VERSION_MAPS
  (CONDITION_DATA_SET_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNFKEYVER_CNFKOCPTMP_FK_I'
CREATE INDEX CNFKEYVER_CNFKOCPTMP_FK_I ON CONFIG_KEY_VERSION_MAPS
  (CONFIG_TYPE_KOC_MAP_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNFKEYVER_CNFKEY_FK_I'
CREATE INDEX CNFKEYVER_CNFKEY_FK_I ON CONFIG_KEY_VERSION_MAPS
  (CONFIG_KEY_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/
Prompt Creating Index 'CREFERS_TO_OPTIONAL_SUBVERS__I'
CREATE INDEX CREFERS_TO_OPTIONAL_SUBVERS__I ON CONFIG_KEY_VERSION_MAPS
  (SUBVERSION_COND_DATA_SET_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNFKOCPTMP_PART_FK_I'
CREATE INDEX CNFKOCPTMP_PART_FK_I ON CONFIG_TYPE_KOC_PART_MAPS
  (PART_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNFKOCPTMP_KNDCND_FK_I'
CREATE INDEX CNFKOCPTMP_KNDCND_FK_I ON CONFIG_TYPE_KOC_PART_MAPS
  (KIND_OF_CONDITION_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNFKOCPTMP_CNFKEYTYP_FK_I'
CREATE INDEX CNFKOCPTMP_CNFKEYTYP_FK_I ON CONFIG_TYPE_KOC_PART_MAPS
  (CONFIG_KEY_TYPE_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERMP_SUBVERS_FK_I'
CREATE INDEX CONVERMP_SUBVERS_FK_I ON CONFIG_VERSION_ALIAS_MAPS
  (CONDITION_DATA_SET_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERALMP_PK'
CREATE UNIQUE INDEX CONVERALMP_PK ON CONFIG_VERSION_ALIAS_MAPS
  (CONFIG_VERSION_ALIAS_MAP_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERALMP_CONVERALS_FK_I'
CREATE INDEX CONVERALMP_CONVERALS_FK_I ON CONFIG_VERSION_ALIAS_MAPS
  (CONFIG_VERSION_ALIAS_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CONVERALMP_CNDTST_FK_I'
CREATE INDEX CONVERALMP_CNDTST_FK_I ON CONFIG_VERSION_ALIAS_MAPS
  (SUBVERSION_COND_DATA_SET_ID ASC)
TABLESPACE CMS_&det._PROCERNIT_DATA
/
