
PROMPT Creating Primary Key on 'CONFIG_KEY'
ALTER TABLE CONFIG_KEY
 ADD (CONSTRAINT CONFIG_KEYS_PK PRIMARY KEY
  (CONFIG_KEY_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'CONFIG_KEY_TYPES'
ALTER TABLE CONFIG_KEY_TYPES
 ADD (CONSTRAINT CONFIG_KEY_TYPES_PK PRIMARY KEY
  (CONFIG_KEY_TYPE_ID)
 USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'CONFIG_TYPE_KOC_PART_MAPS'
ALTER TABLE CONFIG_TYPE_KOC_PART_MAPS
 ADD (CONSTRAINT CONFIG_TYPE_KOC_MAP_PK PRIMARY KEY
  (CONFIG_TYPE_KOC_MAP_ID)
 USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'CONFIG_KEY_ALIASES'
ALTER TABLE CONFIG_KEY_ALIASES
 ADD (CONSTRAINT CONFIG_KEY_ALIASES_PK PRIMARY KEY
  (CONFIG_KEY_ALIAS_ID)
 USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Check Constraint on 'CONFIG_VERSION_ALIASES'
ALTER TABLE CONFIG_VERSION_ALIASES
  ADD CONSTRAINT AVCON_1213204257_IS_RE_001 CHECK (IS_RECORD_DELETED BETWEEN 'F'
  AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T')
/

PROMPT Creating Primary Key on 'CONFIG_VERSION_ALIASES'
ALTER TABLE CONFIG_VERSION_ALIASES
  ADD (CONSTRAINT CONVERALS_PK PRIMARY KEY
    (CONFIG_VERSION_ALIAS_ID)
  USING INDEX
  TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_ALIAS_MAPS ADD (CONSTRAINT
  CONVERKALMP_VERLAL_FK FOREIGN KEY
    (CONFIG_VERSION_ALIAS_ID) REFERENCES CONFIG_VERSION_ALIASES
    (CONFIG_VERSION_ALIAS_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_ALIAS_MAPS ADD (CONSTRAINT
  CONVERKALMP_KEYLAL_FK FOREIGN KEY
    (CONFIG_KEY_ALIAS_ID) REFERENCES CONFIG_KEY_ALIASES
    (CONFIG_KEY_ALIAS_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_ALIAS_MAPS ADD (CONSTRAINT
  CONVERKALMP_KOC_FK FOREIGN KEY
    (KIND_OF_CONDITION_ID) REFERENCES CMS_&det._CORE_COND.KINDS_OF_CONDITIONS
    (KIND_OF_CONDITION_ID))
/

PROMPT Creating Primary Key on 'CONFIG_KEY_VERSION_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_ALIAS_MAPS
  ADD (CONSTRAINT CONVERKEYALMP_PK PRIMARY KEY
    (CONFIG_KEY_VERSION_ALIAS_ID)
  USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

-- CONFIG_VERSION_ALIAS_MAP
PROMPT Creating Primary Key on 'CONFIG_VERSION_ALIAS_MAP'
ALTER TABLE CONFIG_VERSION_ALIAS_MAP
  ADD (CONSTRAINT CONVERALMP_PK PRIMARY KEY
    (CONFIG_VERSION_ALIAS_MAP_ID)
  USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Foreign Key on 'CONFIG_VERSION_ALIAS_MAP'
ALTER TABLE CONFIG_VERSION_ALIAS_MAP ADD (CONSTRAINT
  CREFERS_TO_OPTIONAL_SUBVERS__1 FOREIGN KEY
  (CONDITION_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_VERSION_ALIAS_MAP'
ALTER TABLE CONFIG_VERSION_ALIAS_MAP
  ADD (CONSTRAINT CONVERALMP_CNDTST_FK FOREIGN KEY
  (SUBVERSION_COND_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_VERSION_ALIAS_MAP'
ALTER TABLE CONFIG_VERSION_ALIAS_MAP ADD (CONSTRAINT
  CONVERALMP_CONVERAL_PK FOREIGN KEY
  (CONFIG_VERSION_ALIAS_ID) REFERENCES CONFIG_VERSION_ALIASES
  (CONFIG_VERSION_ALIAS_ID))
/



-- //CONFIG_KEY_ALIAS_MAPS
PROMPT Creating Foreign Key on 'CONFIG_KEY_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_ALIAS_MAPS ADD (CONSTRAINT
  CONKYALMP_CONKAL_FK FOREIGN KEY
    (CONFIG_KEY_ALIAS_ID) REFERENCES CONFIG_KEY_ALIASES
    (CONFIG_KEY_ALIAS_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_ALIAS_MAPS'
ALTER TABLE CONFIG_KEY_ALIAS_MAPS ADD (CONSTRAINT
  CONKYALMP_CONKY_FK FOREIGN KEY
    (CONFIG_KEY_ID) REFERENCES CONFIG_KEY
    (CONFIG_KEY_ID))
/

-- //CONFIG_KEY
PROMPT Creating Foreign Key on 'CONFIG_KEY'
ALTER TABLE CONFIG_KEY ADD (CONSTRAINT
  CONKYS_CONKTYP_FK FOREIGN KEY
    (CONFIG_KEY_TYPE_ID) REFERENCES CONFIG_KEY_TYPES
    (CONFIG_KEY_TYPE_ID))
/

-- CONFIG_TYPE_KOC__PART_MAP
-- //CONFIG_KEY
PROMPT Creating Foreign Key on 'CONFIG_TYPE_KOC_PART_MAPS'
ALTER TABLE CONFIG_TYPE_KOC_PART_MAPS ADD (CONSTRAINT
  CONTKOCPARMP_KOCTYP_FK FOREIGN KEY
    (CONFIG_KEY_TYPE_ID) REFERENCES CONFIG_KEY_TYPES
    (CONFIG_KEY_TYPE_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_TYPE_KOC_PART_MAPS'
ALTER TABLE CONFIG_TYPE_KOC_PART_MAPS ADD (CONSTRAINT
  CONTKOCPARMP_TYPKOC_FK FOREIGN KEY
    (KIND_OF_CONDITION_ID) REFERENCES CMS_&det._CORE_COND.KINDS_OF_CONDITIONS
    (KIND_OF_CONDITION_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_TYPE_KOC_PART_MAPS'
ALTER TABLE CONFIG_TYPE_KOC_PART_MAPS ADD (CONSTRAINT
  CONTKOCPARMP_TYPPRT_FK FOREIGN KEY
    (PART_ID) REFERENCES CMS_&det._CORE_CONSTRUCT.PARTS
    (PART_ID))
/

-- //CONFIG_KEY_VERSION_MAP
PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_MAPS ADD (CONSTRAINT
  CONKVERMP_KYMP_FK FOREIGN KEY
    (CONFIG_KEY_ID) REFERENCES CONFIG_KEY
    (CONFIG_KEY_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_MAPS ADD (CONSTRAINT
  CONKVERMP_TYPMP_FK FOREIGN KEY
    (CONFIG_TYPE_KOC_MAP_ID) REFERENCES CONFIG_TYPE_KOC_PART_MAPS
    (CONFIG_TYPE_KOC_MAP_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_MAPS ADD (CONSTRAINT
  CONKVERMP_KEY_PK FOREIGN KEY
  (CONDITION_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/

PROMPT Creating Foreign Key on 'CONFIG_KEY_VERSION_MAPS'
ALTER TABLE CONFIG_KEY_VERSION_MAPS ADD (CONSTRAINT
  CONKVERMP_KEY_SUBVER_PK FOREIGN KEY
  (SUBVERSION_COND_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/