
PROMPT Granting Object Privileges

--CONFIG_KEY
GRANT SELECT ON CONFIG_KEY TO CMS_&det._CORE_IOV_MGMNT_READER
/
GRANT SELECT ON CONFIG_KEY to PUBLIC
/

GRANT INSERT, UPDATE ON CONFIG_KEY TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_KEY_ALIAS_MAPS
GRANT SELECT ON CONFIG_KEY_ALIAS_MAPS to CMS_&det._CORE_IOV_MGMNT_READER
/
GRANT SELECT ON CONFIG_KEY_ALIAS_MAPS to PUBLIC
/

GRANT INSERT, UPDATE ON CONFIG_KEY_ALIAS_MAPS TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_KEY_ALIASES
GRANT SELECT ON CONFIG_KEY_ALIASES to CMS_&det._CORE_IOV_MGMNT_READER
/
GRANT SELECT ON CONFIG_KEY_ALIASES to PUBLIC
/

GRANT INSERT, UPDATE ON CONFIG_KEY_ALIASES TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_KEY_RUN_HST
GRANT SELECT ON CONFIG_KEY_RUN_HST to CMS_&det._CORE_IOV_MGMNT_READER
/

--CONFIG_KEY_SUBVER_MAPS_HST
GRANT SELECT ON CONFIG_KEY_SUBVER_MAPS_HST to CMS_&det._CORE_IOV_MGMNT_READER
/

--CONFIG_KEY_TYPES
GRANT SELECT ON CONFIG_KEY_TYPES to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT INSERT, UPDATE ON CONFIG_KEY_TYPES TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_KEY_VERSION_ALIAS_MAPS
GRANT SELECT ON CONFIG_KEY_VERSION_ALIAS_MAPS to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT INSERT, UPDATE ON CONFIG_KEY_VERSION_ALIAS_MAPS TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_KEY_VERSION_ALIASES
GRANT SELECT ON CONFIG_VERSION_ALIASES to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT INSERT, UPDATE ON CONFIG_VERSION_ALIASES TO CMS_&det._PRTTYPE_TEST_WRITER
/

-- CONFIG_KEY_VERSION_MAPS
GRANT SELECT ON CONFIG_KEY_VERSION_MAPS to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT SELECT ON CONFIG_KEY_VERSION_MAPS to PUBLIC
/

GRANT INSERT, UPDATE ON CONFIG_KEY_VERSION_MAPS TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_TYPE_KOC_PART_MAPS
GRANT SELECT ON CONFIG_TYPE_KOC_PART_MAPS to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT INSERT, UPDATE ON CONFIG_TYPE_KOC_PART_MAPS TO CMS_&det._PRTTYPE_TEST_WRITER
/

--CONFIG_VERSION_ALIAS_MAP
GRANT SELECT ON CONFIG_VERSION_ALIAS_MAP to CMS_&det._CORE_IOV_MGMNT_READER
/

GRANT INSERT, UPDATE ON CONFIG_VERSION_ALIAS_MAP TO CMS_&det._PRTTYPE_TEST_WRITER
/
