
PROMPT Creating Index 'ATCGHT_ATRCTG_FK_I'
CREATE INDEX ATCGHT_ATRCTG_FK_I ON ATTR_CATALOGS_HST
 (ATTR_CATALOG_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 512K
   NEXT 512K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'EXTPS_ATRBSE_FK_I'
CREATE INDEX EXTPS_ATRBSE_FK_I ON EXT_POSITION_SCHEMAS
 (ATTRIBUTE_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 512K
   NEXT 512K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'PSNSHM_ATRBSE_FK_I'
CREATE INDEX PSNSHM_ATRBSE_FK_I ON POSITION_SCHEMAS
 (ATTRIBUTE_ID)
 PCTFREE 10 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'CNDALG_ATRBSE_FK_I'
CREATE INDEX CNDALG_ATRBSE_FK_I ON COND_ALGORITHMS
 (ATTRIBUTE_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 512K
   NEXT 512K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'ATRBSE_ATRCTG_FK_I'
CREATE INDEX ATRBSE_ATRCTG_FK_I ON ATTR_BASES
 (ATTR_CATALOG_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 512K
   NEXT 512K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'MDESTG_ATRBSE_FK_I'
CREATE INDEX MDESTG_ATRBSE_FK_I ON MODES_STAGES
 (ATTRIBUTE_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 512K
   NEXT 512K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX ATTRCAT_NAME_I ON ATTR_CATALOGS
 (DISPLAY_NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX POSSHEMA_NAME_I ON POSITION_SCHEMAS
 (NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX CNDALGO_NAME_I ON COND_ALGORITHMS
 (NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX MODESTAGE_NAME_I ON MODES_STAGES
 (NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/