PROMPT Creating Primary Key on 'ATTR_CATALOGS_HST'
ALTER TABLE ATTR_CATALOGS_HST
 ADD (CONSTRAINT ATCGHT_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'EXT_POSITION_SCHEMAS'
ALTER TABLE EXT_POSITION_SCHEMAS
 ADD (CONSTRAINT EXTPS_PK PRIMARY KEY 
  (ATTRIBUTE_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'POSITION_SCHEMAS'
ALTER TABLE POSITION_SCHEMAS
 ADD (CONSTRAINT PSNSHM_PK PRIMARY KEY 
  (ATTRIBUTE_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'ATTR_CATALOGS'
ALTER TABLE ATTR_CATALOGS
 ADD (CONSTRAINT ATRCTG_PK PRIMARY KEY 
  (ATTR_CATALOG_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_ALGORITHMS'
ALTER TABLE COND_ALGORITHMS
 ADD (CONSTRAINT CNDALG_PK PRIMARY KEY 
  (ATTRIBUTE_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'ATTR_BASES'
ALTER TABLE ATTR_BASES
 ADD (CONSTRAINT ATRBSE_PK PRIMARY KEY 
  (ATTRIBUTE_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'MODES_STAGES'
ALTER TABLE MODES_STAGES
 ADD (CONSTRAINT MDESTG_PK PRIMARY KEY 
  (ATTRIBUTE_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/


 
PROMPT Creating Check Constraint on 'ATTR_CATALOGS_HST'
ALTER TABLE ATTR_CATALOGS_HST
 ADD (CONSTRAINT AVCON_1143145439_IS_RE_000 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/

PROMPT Creating Check Constraint on 'ATTR_CATALOGS_HST'
ALTER TABLE ATTR_CATALOGS_HST
 ADD (CONSTRAINT AVCON_1143145439_IS_UN_000 CHECK (IS_UNIQUE_WITHIN_PARENT BETWEEN 'F' 
AND 'F' OR IS_UNIQUE_WITHIN_PARENT BETWEEN 'T' AND 'T'))
/

PROMPT Creating Check Constraint on 'ATTR_CATALOGS_HST'
ALTER TABLE ATTR_CATALOGS_HST
    ADD (CONSTRAINT AVCON_1143145439_IS_MULT CHECK (IS_MULTIPLE_ATTRS = 'F' OR IS_MULTIPLE_ATTRS = 'T'))
/

PROMPT Creating Check Constraint on 'POSITION_SCHEMAS'
ALTER TABLE POSITION_SCHEMAS
 ADD (CONSTRAINT AVCON_1143145439_IS_RE_001 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'ATTR_CATALOGS'
ALTER TABLE ATTR_CATALOGS
 ADD (CONSTRAINT AVCON_1143145439_IS_RE_002 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/

PROMPT Creating Check Constraint on 'ATTR_CATALOGS'
ALTER TABLE ATTR_CATALOGS
 ADD (CONSTRAINT AVCON_1143145439_IS_UN_001 CHECK (IS_UNIQUE_WITHIN_PARENT BETWEEN 'F' 
AND 'F' OR IS_UNIQUE_WITHIN_PARENT BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_ALGORITHMS'
ALTER TABLE COND_ALGORITHMS
 ADD (CONSTRAINT AVCON_1143145439_IS_RE_003 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'ATTR_BASES'
ALTER TABLE ATTR_BASES
 ADD (CONSTRAINT AVCON_1143145439_IS_RE_004 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 

PROMPT Creating Foreign Key on 'ATTR_CATALOGS_HST'
ALTER TABLE ATTR_CATALOGS_HST ADD (CONSTRAINT
 ATCGHT_ATRCTG_FK FOREIGN KEY 
  (ATTR_CATALOG_ID) REFERENCES ATTR_CATALOGS
  (ATTR_CATALOG_ID))
/

PROMPT Creating Foreign Key on 'EXT_POSITION_SCHEMAS'
ALTER TABLE EXT_POSITION_SCHEMAS ADD (CONSTRAINT
 EXTPS_ATRBSE_FK FOREIGN KEY 
  (ATTRIBUTE_ID) REFERENCES ATTR_BASES
  (ATTRIBUTE_ID))
/

PROMPT Creating Foreign Key on 'POSITION_SCHEMAS'
ALTER TABLE POSITION_SCHEMAS ADD (CONSTRAINT
 PSNSHM_ATRBSE_FK FOREIGN KEY 
  (ATTRIBUTE_ID) REFERENCES ATTR_BASES
  (ATTRIBUTE_ID))
/

PROMPT Creating Foreign Key on 'COND_ALGORITHMS'
ALTER TABLE COND_ALGORITHMS ADD (CONSTRAINT
 CNDALG_ATRBSE_FK FOREIGN KEY 
  (ATTRIBUTE_ID) REFERENCES ATTR_BASES
  (ATTRIBUTE_ID))
/

PROMPT Creating Foreign Key on 'ATTR_BASES'
ALTER TABLE ATTR_BASES ADD (CONSTRAINT
 ATRBSE_ATRCTG_FK FOREIGN KEY 
  (ATTR_CATALOG_ID) REFERENCES ATTR_CATALOGS
  (ATTR_CATALOG_ID))
/

PROMPT Creating Foreign Key on 'MODES_STAGES'
ALTER TABLE MODES_STAGES ADD (CONSTRAINT
 MDESTG_ATRBSE_FK FOREIGN KEY 
  (ATTRIBUTE_ID) REFERENCES ATTR_BASES
  (ATTRIBUTE_ID))
/


