PROMPT Creating Sequence 'ANY_RLTNSHP_ID_SEQ'
CREATE SEQUENCE ANY_RLTNSHP_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_RLTNSHP_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_RLTNSHP_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ATTR_CATALOG_HISTORY_ID_SEQ'
CREATE SEQUENCE ATTR_CATALOG_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_PREDEFATTR_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_PREDEFATTR_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ATTR_CATALOG_ID_SEQ'
CREATE SEQUENCE ATTR_CATALOG_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_ATTR_LIST_REC_ID_SEQ'
CREATE SEQUENCE ANY_ATTR_LIST_REC_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_KINDOFIFC_ID_SEQ'
CREATE SEQUENCE ANY_KINDOFIFC_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_KINDOFIFC_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_KINDOFIFC_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'PREDEF_ATTR_ID_SEQ'
CREATE SEQUENCE PREDEF_ATTR_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

