PROMPT Granting Object Privileges
GRANT SELECT ON PREDEF_ATTR_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON PREDEF_ATTR_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON PREDEF_ATTR_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON PREDEF_ATTR_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON PREDEF_ATTR_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ATTR_CATALOG_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ATTR_CATALOG_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ATTR_CATALOG_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ATTR_CATALOG_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ATTR_CATALOG_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_RLTNSHP_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ANY_RLTNSHP_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_RLTNSHP_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_RLTNSHP_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_RLTNSHP_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_RLTNSHP_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_RLTNSHP_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_RLTNSHP_HISTORY_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_RLTNSHP_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_RLTNSHP_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ANY_PREDEFATTR_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_PREDEFATTR_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ANY_PREDEFATTR_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_PREDEFATTR_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_PREDEFATTR_HISTORY_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_KINDOFIFC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_KINDOFIFC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_KINDOFIFC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ANY_KINDOFIFC_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_KINDOFIFC_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_KINDOFIFC_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_KINDOFIFC_HISTORY_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_KINDOFIFC_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_KINDOFIFC_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_KINDOFIFC_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ANY_ATTR_LIST_REC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ANY_ATTR_LIST_REC_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ANY_ATTR_LIST_REC_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ANY_ATTR_LIST_REC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ANY_ATTR_LIST_REC_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ATTR_CATALOG_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT SELECT ON ATTR_CATALOG_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ATTR_CATALOG_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ATTR_CATALOG_HISTORY_ID_SEQ TO CMS_&det._CORE_COND
/

GRANT SELECT ON ATTR_CATALOG_HISTORY_ID_SEQ TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON EXT_POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT INSERT, UPDATE ON EXT_POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT DELETE ON EXT_POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT INSERT, UPDATE ON POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT DELETE ON POSITION_SCHEMAS TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT INSERT, UPDATE ON MODES_STAGES TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON MODES_STAGES TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT DELETE ON MODES_STAGES TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON COND_ALGORITHMS TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT INSERT, UPDATE ON COND_ALGORITHMS TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT DELETE ON COND_ALGORITHMS TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT SELECT ON ATTR_CATALOGS_HST TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT DELETE ON ATTR_CATALOGS_HST TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT REFERENCES, SELECT ON ATTR_CATALOGS_HST TO CMS_&det._CORE_COND
/

GRANT INSERT, UPDATE ON ATTR_CATALOGS_HST TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT REFERENCES, SELECT ON ATTR_CATALOGS TO CMS_&det._CORE_COND
/

GRANT INSERT, UPDATE ON ATTR_CATALOGS TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT SELECT ON ATTR_CATALOGS TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT DELETE ON ATTR_CATALOGS TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT REFERENCES, SELECT ON ATTR_CATALOGS TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON ATTR_BASES TO CMS_&det._CORE_ATTRIBUTE_READER
/

GRANT REFERENCES, SELECT ON ATTR_BASES TO CMS_&det._CORE_CONSTRUCT
/

GRANT REFERENCES, SELECT ON ATTR_BASES TO CMS_&det._&subdet._CONSTRUCT
/

GRANT DELETE ON ATTR_BASES TO CMS_&det._CORE_ATTRIBUTE_ADMIN
/

GRANT INSERT, UPDATE ON ATTR_BASES TO CMS_&det._CORE_CONDITION_WRITER
/

GRANT INSERT, UPDATE ON ATTR_BASES TO CMS_&det._CORE_ATTRIBUTE_WRITER
/

GRANT REFERENCES, SELECT ON ATTR_BASES TO CMS_&det._CORE_COND
/


