CREATE VIEW CMS_&det._CORE_ATTRIBUTE.V_ANY_ATTR_CATALOGS AS SELECT D.ATTRIBUTE_ID,C.ATTR_CATALOG_ID,
D.NAME AS ATTR_VALUE,
C.DISPLAY_NAME AS ATTR_CATALOG_NAME,
C.IS_UNIQUE_WITHIN_PARENT,
B.EXTENSION_TABLE_NAME
FROM (SELECT ATTRIBUTE_ID, NAME, IS_RECORD_DELETED FROM COND_ALGORITHMS
UNION SELECT ATTRIBUTE_ID, NAME, IS_RECORD_DELETED FROM EXT_POSITION_SCHEMAS
UNION SELECT ATTRIBUTE_ID, NAME, IS_RECORD_DELETED FROM MODES_STAGES
UNION SELECT ATTRIBUTE_ID, NAME, IS_RECORD_DELETED FROM POSITION_SCHEMAS) D
INNER JOIN ATTR_BASES B
ON  D.ATTRIBUTE_ID = B.ATTRIBUTE_ID
INNER JOIN ATTR_CATALOGS C
ON C.ATTR_CATALOG_ID = B.ATTR_CATALOG_ID
WHERE C.IS_RECORD_DELETED='F' AND B.IS_RECORD_DELETED='F' AND D.IS_RECORD_DELETED='F'
/

CREATE VIEW CMS_&det._CORE_ATTRIBUTE.V_COND_ALGORITHMS AS SELECT D.ATTRIBUTE_ID, D.NAME,
D.COMMENT_DESCRIPTION,
D.SOFTWARE_RELEASE_VERSION,
C.ATTR_CATALOG_ID, C.DISPLAY_NAME,
C.IS_UNIQUE_WITHIN_PARENT,
C.COMMENT_DESCRIPTION AS CAT_COMMENT_DESCRIPTION
 FROM COND_ALGORITHMS D
  INNER JOIN ATTR_BASES B
  ON D.ATTRIBUTE_ID=B.ATTRIBUTE_ID
  INNER JOIN ATTR_CATALOGS C
  ON C.ATTR_CATALOG_ID = B.ATTR_CATALOG_ID
  WHERE C.IS_RECORD_DELETED='F' AND B.IS_RECORD_DELETED='F' AND D.IS_RECORD_DELETED='F'
/

CREATE VIEW CMS_&det._CORE_ATTRIBUTE.V_EXT_POSITION_SCHEMAS AS SELECT D.ATTRIBUTE_ID, D.NAME,
D.ALIAS_A,
D.ALIAS_B,
D.ALIAS_C,
D.COMMENT_DESCRIPTION,
C.ATTR_CATALOG_ID, C.DISPLAY_NAME,
C.IS_UNIQUE_WITHIN_PARENT,
C.COMMENT_DESCRIPTION AS CAT_COMMENT_DESCRIPTION
 FROM EXT_POSITION_SCHEMAS D
  INNER JOIN ATTR_BASES B
  ON D.ATTRIBUTE_ID=B.ATTRIBUTE_ID
  INNER JOIN ATTR_CATALOGS C
  ON C.ATTR_CATALOG_ID = B.ATTR_CATALOG_ID
  WHERE C.IS_RECORD_DELETED='F' AND B.IS_RECORD_DELETED='F' AND D.IS_RECORD_DELETED='F'
/

CREATE VIEW CMS_&det._CORE_ATTRIBUTE.V_MODES_STAGES AS SELECT D.ATTRIBUTE_ID, D.NAME,
D.COMMENT_DESCRIPTION,
C.ATTR_CATALOG_ID, C.DISPLAY_NAME,
C.IS_UNIQUE_WITHIN_PARENT,
C.COMMENT_DESCRIPTION AS CAT_COMMENT_DESCRIPTION
 FROM MODES_STAGES D
  INNER JOIN ATTR_BASES B
  ON D.ATTRIBUTE_ID=B.ATTRIBUTE_ID
  INNER JOIN ATTR_CATALOGS C
  ON C.ATTR_CATALOG_ID = B.ATTR_CATALOG_ID
  WHERE C.IS_RECORD_DELETED='F' AND B.IS_RECORD_DELETED='F' AND D.IS_RECORD_DELETED='F'
/

CREATE VIEW CMS_&det._CORE_ATTRIBUTE.V_POSITION_SCHEMAS AS SELECT D.ATTRIBUTE_ID, D.NAME,
C.ATTR_CATALOG_ID, C.DISPLAY_NAME,
C.IS_UNIQUE_WITHIN_PARENT,
C.COMMENT_DESCRIPTION AS CAT_COMMENT_DESCRIPTION
 FROM POSITION_SCHEMAS D
  INNER JOIN ATTR_BASES B
  ON D.ATTRIBUTE_ID=B.ATTRIBUTE_ID
  INNER JOIN ATTR_CATALOGS C
  ON C.ATTR_CATALOG_ID = B.ATTR_CATALOG_ID
  WHERE C.IS_RECORD_DELETED='F' AND B.IS_RECORD_DELETED='F' AND D.IS_RECORD_DELETED='F'
/

