
PROMPT Creating User 'CMS_&det._PRTTYPE_&subdet._WRITER'
CREATE USER CMS_&det._PRTTYPE_&subdet._WRITER IDENTIFIED BY &writer_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
/
GRANT CMS_&det._&subdet._APP_WRITER TO CMS_&det._PRTTYPE_&subdet._WRITER 
/
GRANT CMS_&det._USER_ROLE TO CMS_&det._PRTTYPE_&subdet._WRITER 
/

PROMPT Creating User 'CMS_&det._CORE_IOV_MGMNT'
CREATE USER CMS_&det._CORE_IOV_MGMNT IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._CORE_IOV_MGMNT 
/

PROMPT Creating User 'CMS_&det._&subdet._CONSTRUCT'
CREATE USER CMS_&det._&subdet._CONSTRUCT IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._&subdet._CONSTRUCT 
/

PROMPT Creating User 'CMS_&det._PRTTYPE_&subdet._READER'
CREATE USER CMS_&det._PRTTYPE_&subdet._READER IDENTIFIED BY &reader_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
/
GRANT CMS_&det._USER_ROLE TO CMS_&det._PRTTYPE_&subdet._READER 
/
GRANT CMS_&det._&subdet._APP_READER TO CMS_&det._PRTTYPE_&subdet._READER 
/

PROMPT Creating User 'CMS_&det._&subdet._COND'
CREATE USER CMS_&det._&subdet._COND IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._&subdet._COND 
/


PROMPT Creating User 'CMS_&det._CORE_COND'
CREATE USER CMS_&det._CORE_COND IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._CORE_COND 
/

PROMPT Creating User 'CMS_&det._PRTTYPE_&subdet._ADMIN'
CREATE USER CMS_&det._PRTTYPE_&subdet._ADMIN IDENTIFIED BY &admin_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
/
GRANT CMS_&det._USER_ROLE TO CMS_&det._PRTTYPE_&subdet._ADMIN 
/
GRANT CMS_&det._&subdet._APP_ADMIN TO CMS_&det._PRTTYPE_&subdet._ADMIN 
/

PROMPT Creating User 'CMS_&det._CORE_CONSTRUCT'
CREATE USER CMS_&det._CORE_CONSTRUCT IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._CORE_CONSTRUCT 
/

PROMPT Creating User 'CMS_&det._CORE_ATTRIBUTE'
CREATE USER CMS_&det._CORE_ATTRIBUTE IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._CORE_ATTRIBUTE 
/

PROMPT Creating User 'CMS_&det._CORE_MANAGEMNT'
CREATE USER CMS_&det._CORE_MANAGEMNT IDENTIFIED BY &owner_password
  DEFAULT TABLESPACE CMS_&det._PROCERNIT_DATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CMS_&det._PROCERNIT_DATA
/
GRANT CMS_&det._SCHEMA_OWNER_ROLE TO CMS_&det._CORE_MANAGEMNT 
/

create user cms_&det._&subdet._view identified by &view_password 
default tablespace CMS_&det._PROCERNIT_DATA 
temporary tablespace TEMP
/

grant cms_&det._&subdet._app_reader, cms_&det._schema_owner_role to cms_&det._&subdet._view
/
