
PROMPT Creating Primary Key on 'KIND_OF_CONDITIONS_HST'
ALTER TABLE KIND_OF_CONDITIONS_HST
 ADD (CONSTRAINT KOCHT_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS
 ADD (CONSTRAINT CNDTST_PK PRIMARY KEY 
  (CONDITION_DATA_SET_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_TO_ATTR_RLTNSHPS_HST'
ALTER TABLE COND_TO_ATTR_RLTNSHPS_HST
 ADD (CONSTRAINT CARHST_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_TO_PART_RLTNSHPS'
ALTER TABLE COND_TO_PART_RLTNSHPS
 ADD (CONSTRAINT CNPTREL_PK PRIMARY KEY 
  (RELATIONSHIP_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_TO_ATTR_RLTNSHPS'
ALTER TABLE COND_TO_ATTR_RLTNSHPS
 ADD (CONSTRAINT CNATRL_PK PRIMARY KEY 
  (RELATIONSHIP_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'KINDS_OF_CONDITIONS'
ALTER TABLE KINDS_OF_CONDITIONS
 ADD (CONSTRAINT KNDCND_PK PRIMARY KEY 
  (KIND_OF_CONDITION_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS
 ADD (CONSTRAINT CNATLS_PK PRIMARY KEY 
  (ATTR_LIST_RECORD_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'CHANNEL_MAPS_BASE'
ALTER TABLE CHANNEL_MAPS_BASE
 ADD (CONSTRAINT CHMPBS_PK PRIMARY KEY 
  (CHANNEL_MAP_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_TO_PART_RLTNSHPS_HST'
ALTER TABLE COND_TO_PART_RLTNSHPS_HST
 ADD (CONSTRAINT CPTHST_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_RUNS'
ALTER TABLE COND_RUNS
 ADD (CONSTRAINT CNDRUN_PK PRIMARY KEY 
  (COND_RUN_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'COND_RUNS_HST'
ALTER TABLE COND_RUNS_HST
 ADD (CONSTRAINT CNRNHT_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/


PROMPT Creating Unique Key on 'COND_TO_ATTR_RLTNSHPS'
ALTER TABLE COND_TO_ATTR_RLTNSHPS
 ADD (CONSTRAINT CNATRL_DISP_NAME_UK UNIQUE 
  (DISPLAY_NAME)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Unique Key on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS
 ADD (CONSTRAINT CATLST_CONDATTRLSTENTRY_UK_UK UNIQUE 
  (ATTRIBUTE_ID
  ,RELATIONSHIP_ID
  ,CONDITION_DATA_SET_ID)
 USING INDEX 
 PCTFREE 10
 STORAGE
 (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA)
/

 
PROMPT Creating Check Constraint on 'KIND_OF_CONDITIONS_HST'
ALTER TABLE KIND_OF_CONDITIONS_HST
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_000 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_002 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_TO_ATTR_RLTNSHPS_HST'
ALTER TABLE COND_TO_ATTR_RLTNSHPS_HST
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_003 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_TO_PART_RLTNSHPS'
ALTER TABLE COND_TO_PART_RLTNSHPS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_004 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_TO_ATTR_RLTNSHPS'
ALTER TABLE COND_TO_ATTR_RLTNSHPS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_005 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'KINDS_OF_CONDITIONS'
ALTER TABLE KINDS_OF_CONDITIONS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_007 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_009 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'CHANNEL_MAPS_BASE'
ALTER TABLE CHANNEL_MAPS_BASE
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_011 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_TO_PART_RLTNSHPS_HST'
ALTER TABLE COND_TO_PART_RLTNSHPS_HST
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_012 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_RUNS'
ALTER TABLE COND_RUNS
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_013 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'COND_RUNS_HST'
ALTER TABLE COND_RUNS_HST
 ADD (CONSTRAINT AVCON_1135111810_IS_RE_014 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/


PROMPT Creating Foreign Key on 'KIND_OF_CONDITIONS_HST'
ALTER TABLE KIND_OF_CONDITIONS_HST ADD (CONSTRAINT
 KOCHT_KNDCND_FK FOREIGN KEY 
  (KIND_OF_CONDITION_ID) REFERENCES KINDS_OF_CONDITIONS
  (KIND_OF_CONDITION_ID))
/

PROMPT Creating Foreign Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS ADD (CONSTRAINT
 CNDTST_CHMPBS_FK FOREIGN KEY 
  (CHANNEL_MAP_ID) REFERENCES CMS_&det._CORE_COND.CHANNEL_MAPS_BASE
  (CHANNEL_MAP_ID))
/

PROMPT Creating Foreign Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS ADD (CONSTRAINT
 CNDTST_CNDRUN_FK FOREIGN KEY 
  (COND_RUN_ID) REFERENCES COND_RUNS
  (COND_RUN_ID))
/

PROMPT Creating Foreign Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS ADD (CONSTRAINT
 CNDTST_KNDCND_FK FOREIGN KEY 
  (KIND_OF_CONDITION_ID) REFERENCES KINDS_OF_CONDITIONS
  (KIND_OF_CONDITION_ID))
/

PROMPT Creating Foreign Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS ADD (CONSTRAINT
 CNDTST_CNDTST_FK FOREIGN KEY 
  (AGGREGATED_COND_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/

PROMPT Creating Foreign Key on 'COND_DATA_SETS'
ALTER TABLE COND_DATA_SETS ADD (CONSTRAINT
 CNDTST_PRTTREE_FK FOREIGN KEY 
  (PART_ID) REFERENCES CMS_&det._CORE_CONSTRUCT.PHYSICAL_PARTS_TREE
  (PART_ID) DISABLE)
/

PROMPT Creating Foreign Key on 'COND_TO_ATTR_RLTNSHPS_HST'
ALTER TABLE COND_TO_ATTR_RLTNSHPS_HST ADD (CONSTRAINT
 CARHST_CNATRL_FK FOREIGN KEY 
  (RELATIONSHIP_ID) REFERENCES COND_TO_ATTR_RLTNSHPS
  (RELATIONSHIP_ID))
/

PROMPT Creating Foreign Key on 'COND_TO_PART_RLTNSHPS'
ALTER TABLE COND_TO_PART_RLTNSHPS ADD (CONSTRAINT
 CNPTREL_KNDPRT_FK FOREIGN KEY 
  (KIND_OF_PART_ID) REFERENCES CMS_&det._CORE_CONSTRUCT.KINDS_OF_PARTS
  (KIND_OF_PART_ID))
/

PROMPT Creating Foreign Key on 'COND_TO_PART_RLTNSHPS'
ALTER TABLE COND_TO_PART_RLTNSHPS ADD (CONSTRAINT
 CNPTREL_KNDCND_FK FOREIGN KEY 
  (KIND_OF_CONDITION_ID) REFERENCES KINDS_OF_CONDITIONS
  (KIND_OF_CONDITION_ID))
/

PROMPT Creating Foreign Key on 'COND_TO_ATTR_RLTNSHPS'
ALTER TABLE COND_TO_ATTR_RLTNSHPS ADD (CONSTRAINT
 CNATRL_ATRCTG_FK FOREIGN KEY 
  (ATTR_CATALOG_ID) REFERENCES CMS_&det._CORE_ATTRIBUTE.ATTR_CATALOGS
  (ATTR_CATALOG_ID))
/

PROMPT Creating Foreign Key on 'COND_TO_ATTR_RLTNSHPS'
ALTER TABLE COND_TO_ATTR_RLTNSHPS ADD (CONSTRAINT
 CNATRL_KNDCND_FK FOREIGN KEY 
  (KIND_OF_CONDITION_ID) REFERENCES KINDS_OF_CONDITIONS
  (KIND_OF_CONDITION_ID))
/

PROMPT Creating Foreign Key on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS ADD (CONSTRAINT
 CNATLS_CNDTST_FK FOREIGN KEY 
  (CONDITION_DATA_SET_ID) REFERENCES CMS_&det._CORE_COND.COND_DATA_SETS
  (CONDITION_DATA_SET_ID))
/

PROMPT Creating Foreign Key on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS ADD (CONSTRAINT
 CNATLS_ATRBSE_FK FOREIGN KEY 
  (ATTRIBUTE_ID) REFERENCES CMS_&det._CORE_ATTRIBUTE.ATTR_BASES
  (ATTRIBUTE_ID))
/

PROMPT Creating Foreign Key on 'COND_ATTR_LISTS'
ALTER TABLE COND_ATTR_LISTS ADD (CONSTRAINT
 CNATLS_CNATRL_FK FOREIGN KEY 
  (RELATIONSHIP_ID) REFERENCES COND_TO_ATTR_RLTNSHPS
  (RELATIONSHIP_ID))
/

PROMPT Creating Foreign Key on 'COND_TO_PART_RLTNSHPS_HST'
ALTER TABLE COND_TO_PART_RLTNSHPS_HST ADD (CONSTRAINT
 CPTHST_CNPTREL_FK FOREIGN KEY 
  (RELATIONSHIP_ID) REFERENCES COND_TO_PART_RLTNSHPS
  (RELATIONSHIP_ID))
/

PROMPT Creating Foreign Key on 'COND_RUNS_HST'
ALTER TABLE COND_RUNS_HST ADD (CONSTRAINT
 CNRNHT_CNDRUN_FK FOREIGN KEY 
  (COND_RUN_ID) REFERENCES COND_RUNS
  (COND_RUN_ID))
/


