
PROMPT Creating Sequence 'ANY_COND_RECORD_ID_SEQ'
CREATE SEQUENCE ANY_COND_RECORD_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'COND_RUN_HISTORY_ID_SEQ'
CREATE SEQUENCE COND_RUN_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'COND_RUN_ID_SEQ'
CREATE SEQUENCE COND_RUN_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'COND_DATA_SET_ID_SEQ'
CREATE SEQUENCE COND_DATA_SET_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

GRANT SELECT ON  CMS_&det._CORE_COND.COND_RUN_ID_SEQ TO CMS_&det._CORE_CONDITION_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_COND.COND_RUN_ID_SEQ TO CMS_&det._CORE_CONDITION_WRITER;

GRANT SELECT ON  CMS_&det._CORE_COND.COND_RUN_HISTORY_ID_SEQ TO CMS_&det._CORE_CONDITION_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_COND.COND_RUN_HISTORY_ID_SEQ TO CMS_&det._CORE_CONDITION_WRITER;

GRANT SELECT ON  CMS_&det._CORE_COND.COND_DATA_SET_ID_SEQ TO CMS_&det._CORE_CONDITION_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_COND.COND_DATA_SET_ID_SEQ TO CMS_&det._CORE_CONDITION_WRITER;

GRANT SELECT ON  CMS_&det._CORE_COND.ANY_COND_RECORD_ID_SEQ TO CMS_&det._CORE_CONDITION_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_COND.ANY_COND_RECORD_ID_SEQ TO CMS_&det._CORE_CONDITION_WRITER;

