#!/bin/sh
#
# cmsdbldr        Startup script for the CMS DB Loader service
#
# chkconfig: 45 75 25
# description: CMS DB Loader provides XML data upload to Oracle database function.
# processname: cmsdbldr
# config: /opt/cmsdbldr/bin/config.py
# pidfile: /var/run/cmsdbldr.pid
#
### BEGIN INIT INFO
# Provides: cmsdbldr
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Should-Start: distcache
# Short-Description: start and stop CMS DB Loader service
# Description: CMS DB Loader provides XML data upload to Oracle database function.
### END INIT INFO

prog=/usr/bin/uwsgi
name=cmsdbldr
asuser=dbspool
pidfile=/var/run/$name.pid
timeout=3

. /etc/rc.d/init.d/functions

do_start () {
    echo $"Starting $name:"
    touch $pidfile
    chown $asuser $pidfile
    su - $asuser -c "$prog --ini /opt/cmsdbldr/web/uwsgi.ini"
    RETVAL=$?
    echo
    return $RETVAL
}

do_stop () {
    echo -n $"Stopping $name: "
    killproc -p ${pidfile} -d ${timeout} $prog
    RETVAL=$?
    echo
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status -p ${pidfile} $name
	RETVAL=$?
        ;;

    *)
        echo "Usage: /etc/init.d/$name {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
