
PROMPT Creating Index 'USER_1_INSTTN_FK_I'
CREATE INDEX USER_1_INSTTN_FK_I ON USERS
 (INSTITUTION_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'LOCATN_INSTTN_FK_I'
CREATE INDEX LOCATN_INSTTN_FK_I ON LOCATIONS
 (INSTITUTION_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'LOCHST_LOCATN_FK_I'
CREATE INDEX LOCHST_LOCATN_FK_I ON LOCATIONS_HST
 (LOCATION_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'INSTHST_INSTTN_FK_I'
CREATE INDEX INSTHST_INSTTN_FK_I ON INSTITUTIONS_HST
 (INSTITUTION_ID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX USERS_NAME_I ON USERS
 (CCUID)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX LOCATIONS_NAME_I ON LOCATIONS
 (LOCATION_NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX INSTITUTIONS_NAME_I ON INSTITUTIONS
 (NAME)
 PCTFREE 10
 STORAGE
 (
   INITIAL 256K
   NEXT 256K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS UNLIMITED
 ) TABLESPACE CMS_&det._PROCERNIT_DATA
/