
PROMPT Creating Index 'USER_1_INSTTN_FK_I'
CREATE INDEX USER_1_INSTTN_FK_I ON USERS
 (INSTITUTION_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'LOCATN_INSTTN_FK_I'
CREATE INDEX LOCATN_INSTTN_FK_I ON LOCATIONS
 (INSTITUTION_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'LOCHST_LOCATN_FK_I'
CREATE INDEX LOCHST_LOCATN_FK_I ON LOCATIONS_HST
 (LOCATION_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

PROMPT Creating Index 'INSTHST_INSTTN_FK_I'
CREATE INDEX INSTHST_INSTTN_FK_I ON INSTITUTIONS_HST
 (INSTITUTION_ID)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX LOCATIONS_NAME_I ON LOCATIONS
 (LOCATION_NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/

CREATE INDEX INSTITUTIONS_NAME_I ON INSTITUTIONS
 (NAME)
 TABLESPACE CMS_&det._PROCERNIT_DATA
/