
PROMPT Creating Primary Key on 'USERS'
ALTER TABLE USERS
 ADD (CONSTRAINT USER_PK PRIMARY KEY 
  (LOGIN_NAME
  ,RECORD_ID)
 USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'LOCATIONS'
ALTER TABLE LOCATIONS
 ADD (CONSTRAINT LOCATN_PK PRIMARY KEY 
  (LOCATION_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'LOCATIONS_HST'
ALTER TABLE LOCATIONS_HST
 ADD (CONSTRAINT LOCHST_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'INSTITUTIONS'
ALTER TABLE INSTITUTIONS
 ADD (CONSTRAINT INSTTN_PK PRIMARY KEY 
  (INSTITUTION_ID)
 USING INDEX
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/

PROMPT Creating Primary Key on 'INSTITUTIONS_HST'
ALTER TABLE INSTITUTIONS_HST
 ADD (CONSTRAINT INSTHST_PK PRIMARY KEY 
  (HISTORY_RECORD_ID)
 USING INDEX 
 TABLESPACE CMS_&det._PROCERNIT_DATA)
/


 
PROMPT Creating Check Constraint on 'USERS'
ALTER TABLE USERS
 ADD (CONSTRAINT AVCON_1135112388_IS_RE_000 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'LOCATIONS'
ALTER TABLE LOCATIONS
 ADD (CONSTRAINT AVCON_1135112388_IS_RE_001 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'LOCATIONS_HST'
ALTER TABLE LOCATIONS_HST
 ADD (CONSTRAINT AVCON_1135112388_IS_RE_002 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'INSTITUTIONS'
ALTER TABLE INSTITUTIONS
 ADD (CONSTRAINT AVCON_1135112388_IS_RE_003 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/
 
PROMPT Creating Check Constraint on 'INSTITUTIONS_HST'
ALTER TABLE INSTITUTIONS_HST
 ADD (CONSTRAINT AVCON_1135112388_IS_RE_004 CHECK (IS_RECORD_DELETED BETWEEN 'F' 
AND 'F' OR IS_RECORD_DELETED BETWEEN 'T' AND 'T'))
/


PROMPT Creating Foreign Key on 'USERS'
ALTER TABLE USERS ADD (CONSTRAINT
 USER_INSTTN_FK FOREIGN KEY 
  (INSTITUTION_ID) REFERENCES INSTITUTIONS
  (INSTITUTION_ID))
/

PROMPT Creating Foreign Key on 'LOCATIONS'
ALTER TABLE LOCATIONS ADD (CONSTRAINT
 LOCATN_INSTTN_FK FOREIGN KEY 
  (INSTITUTION_ID) REFERENCES INSTITUTIONS
  (INSTITUTION_ID))
/

PROMPT Creating Foreign Key on 'LOCATIONS_HST'
ALTER TABLE LOCATIONS_HST ADD (CONSTRAINT
 LOCHST_LOCATN_FK FOREIGN KEY 
  (LOCATION_ID) REFERENCES CMS_&det._CORE_MANAGEMNT.LOCATIONS
  (LOCATION_ID))
/

PROMPT Creating Foreign Key on 'INSTITUTIONS_HST'
ALTER TABLE INSTITUTIONS_HST ADD (CONSTRAINT
 INSTHST_INSTTN_FK FOREIGN KEY 
  (INSTITUTION_ID) REFERENCES INSTITUTIONS
  (INSTITUTION_ID))
/


