
PROMPT Creating Sequence 'ANY_INSTITUTION_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_INSTITUTION_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_USER_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_USER_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_INSTITUTION_ID_SEQ'
CREATE SEQUENCE ANY_INSTITUTION_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_LOCATION_ID_SEQ'
CREATE SEQUENCE ANY_LOCATION_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_USER_ID_SEQ'
CREATE SEQUENCE ANY_USER_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

PROMPT Creating Sequence 'ANY_LOCATION_HISTORY_ID_SEQ'
CREATE SEQUENCE ANY_LOCATION_HISTORY_ID_SEQ
 INCREMENT BY 20
 START WITH 1000
 NOMAXVALUE
 MINVALUE 1000
 NOCYCLE
 CACHE 20
/

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN;

GRANT SELECT ON  CMS_&det._CORE_MANAGEMNT.ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER;

