
PROMPT Granting Object Privileges
GRANT SELECT ON ANY_USER_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON ANY_USER_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/

GRANT SELECT ON ANY_USER_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/


GRANT SELECT ON ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/

GRANT SELECT ON ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON ANY_USER_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/


GRANT SELECT ON ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON ANY_LOCATION_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/


GRANT SELECT ON ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/

GRANT SELECT ON ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON ANY_LOCATION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/


GRANT SELECT ON ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/

GRANT SELECT ON ANY_INSTITUTION_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/


GRANT SELECT ON ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON ANY_INSTITUTION_HISTORY_ID_SEQ TO CMS_&det._CORE_ATTRIBUTE
/


GRANT INSERT, UPDATE ON USERS TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON USERS TO CMS_&det._CORE_MANAGEMNT_READER
/

GRANT REFERENCES, SELECT ON USERS TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON USERS TO CMS_&det._CORE_ATTRIBUTE
/

GRANT DELETE ON USERS TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT REFERENCES, SELECT ON USERS TO CMS_&det._CORE_COND
/


GRANT INSERT, UPDATE ON LOCATIONS_HST TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT DELETE ON LOCATIONS_HST TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT SELECT ON LOCATIONS_HST TO CMS_&det._CORE_ATTRIBUTE
/

GRANT SELECT ON LOCATIONS_HST TO CMS_&det._CORE_MANAGEMNT_READER
/


GRANT INSERT, UPDATE ON LOCATIONS TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT REFERENCES, SELECT ON LOCATIONS TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON LOCATIONS TO CMS_&det._CORE_MANAGEMNT_READER
/

GRANT SELECT ON LOCATIONS TO CMS_&det._CORE_ATTRIBUTE
/

GRANT DELETE ON LOCATIONS TO CMS_&det._CORE_MANAGEMNT_ADMIN
/


GRANT SELECT ON INSTITUTIONS_HST TO CMS_&det._CORE_MANAGEMNT_READER
/

GRANT DELETE ON INSTITUTIONS_HST TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT INSERT, UPDATE ON INSTITUTIONS_HST TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON INSTITUTIONS_HST TO CMS_&det._CORE_ATTRIBUTE
/


GRANT REFERENCES, SELECT ON INSTITUTIONS TO CMS_&det._CORE_CONSTRUCT
/

GRANT SELECT ON INSTITUTIONS TO CMS_&det._CORE_ATTRIBUTE
/

GRANT INSERT, UPDATE ON INSTITUTIONS TO CMS_&det._CORE_MANAGEMNT_WRITER
/

GRANT SELECT ON INSTITUTIONS TO CMS_&det._CORE_MANAGEMNT_READER
/

GRANT DELETE ON INSTITUTIONS TO CMS_&det._CORE_MANAGEMNT_ADMIN
/

GRANT REFERENCES, SELECT ON INSTITUTIONS TO CMS_&det._&subdet._CONSTRUCT
/

GRANT REFERENCES, SELECT ON LOCATIONS TO CMS_&det._&subdet._CONSTRUCT
/
